import { create } from 'zustand';
import { persist, createJSONStorage, type StateStorage } from 'zustand/middleware';

const generateId = () => {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  return 'id-' + Date.now() + '-' + Math.random().toString(36).substring(2, 9);
};

export type GameStatus = 'Owned' | 'Owned by Friends' | 'Wishlist' | 'Preorder' | 'None';

export interface Game {
  id: string;
  title: string;
  subtitle?: string; // Optional subtitle (e.g., Korean title)
  players: string; // e.g., '2-5'
  duration?: number | string; // Duration in minutes (e.g. 60 or '60-90')
  playTime?: number | string; // Legacy fallback
  weight: number; // 1.0 - 5.0
  imageUrl: string;
  totalPlays: number;
  publishedYear?: number;
  status?: GameStatus; // Ownership status
  bggUrl?: string; // BGG page URL
}

export interface Player {
  id: string;
  name: string;
  group: 'Family' | 'Friend' | 'User';
  imageUrl?: string;
}

export interface PlayerScore {
  playerId: string;
  score: number;
}

export interface PlayLog {
  id: string;
  gameId: string;
  date: string; // ISO string
  players: PlayerScore[];
  winnerIds: string[]; // All 1st-place winners (1 for sole winner, >1 for ties)
  reviewMemo: string;
  imageUrls?: string[]; // New: support for uploaded photographs
}

export interface BoardGameStory {
  id: string;
  title: string;
  description: string;
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
  coverGradient: string; // Tailwind gradient class, e.g., "from-indigo-950 via-slate-900 to-blue-900"
  createdDate: string; // ISO string
}

interface BoardGameState {
  games: Game[];
  players: Player[];
  logs: PlayLog[];
  stories: BoardGameStory[];
  _hasHydrated: boolean;
  setHasHydrated: (state: boolean) => void;
  
  // Actions
  addGame: (game: Omit<Game, 'id' | 'totalPlays'>) => void;
  updateGame: (id: string, game: Partial<Game>) => void;
  deleteGame: (id: string) => void;
  
  addPlayer: (player: Omit<Player, 'id'>) => void;
  updatePlayer: (id: string, player: Partial<Player>) => void;
  deletePlayer: (id: string) => void;
  
  addLog: (log: Omit<PlayLog, 'id'>) => void;
  updateLog: (id: string, logData: Partial<PlayLog>) => void;
  deleteLog: (id: string) => void;
  
  addStory: (story: Omit<BoardGameStory, 'id' | 'createdDate'>) => void;
  updateStory: (id: string, story: Partial<BoardGameStory>) => void;
  deleteStory: (id: string) => void;
  
  importData: (data: { games: Game[], players: Player[], logs: PlayLog[], stories?: BoardGameStory[] }) => void;
}

// Initial dummy data to showcase the app
const initialGames: Game[] = [
  {
    "id": "342942",
    "title": "Ark Nova",
    "players": "1-4",
    "playTime": "90-150",
    "weight": 3.8,
    "imageUrl": "https://cdn.shoplightspeed.com/shops/636231/files/38772737/1652x1652x2/capstone-games-ark-nova.jpg",
    "totalPlays": 35,
    "publishedYear": 2021,
    "subtitle": "아크 노바",
    "bggUrl": "https://boardgamegeek.com/boardgame/342942",
    "duration": "90-150",
  },
  {
    "id": "167791",
    "title": "Terraforming Mars",
    "players": "1-5",
    "playTime": "120",
    "weight": 3.3,
    "imageUrl": "https://thedicetroyers.com/wp-content/uploads/2020/06/TheDicetroyers_Terraforming-Mars-All-In-Lifted-Base-02.jpg",
    "totalPlays": 0,
    "publishedYear": 2016,
    "subtitle": "테라포밍 마스",
    "bggUrl": "https://boardgamegeek.com/boardgame/167791",
    "duration": "120",
  },
  {
    "id": "169786",
    "title": "Scythe",
    "players": "1-5",
    "playTime": "90-115",
    "weight": 3.5,
    "imageUrl": "https://www.boardgamequest.com/wp-content/uploads/2017/10/Scythe-The-Wind-Gambit.jpg",
    "totalPlays": 0,
    "publishedYear": 2016,
    "subtitle": "사이드",
    "status": "Owned",
    "bggUrl": "https://boardgamegeek.com/boardgame/169786",
    "duration": "90-115",
  },
  {
    "id": "295947",
    "title": "Cascadia",
    "players": "1-4",
    "playTime": "30-45",
    "weight": 1.8,
    "imageUrl": "https://www.geekyhobbies.com/wp-content/uploads/2025/10/Cascadia-Box-728x410.jpg.webp",
    "totalPlays": 0,
    "publishedYear": 2021,
    "subtitle": "캐스캐디아",
    "bggUrl": "https://boardgamegeek.com/boardgame/295947",
    "duration": "30-45",
  },
  {
    "id": "271320",
    "title": "The Castles of Burgundy",
    "players": "1-4",
    "playTime": "70-120",
    "weight": 2.9,
    "imageUrl": "https://media.printables.com/media/prints/941234/images/7195899_f7bb400f-4021-4776-a7e5-7a0b3b7a0919_c9c39d5e-ac34-44a4-ab88-05b12c59974d/thumbs/inside/1280x960/jpg/duchy_comparison.webp",
    "totalPlays": 2,
    "publishedYear": 2019,
    "subtitle": "버건디의 성",
    "bggUrl": "https://boardgamegeek.com/boardgame/271320",
    "duration": "70-120",
    "status": "Owned",
  },
  {
    "id": "173346",
    "title": "7 Wonders Duel",
    "players": "2",
    "playTime": "30",
    "weight": 2.2,
    "imageUrl": "https://makerworld.bblmw.com/makerworld/model/UScc66dc3aa8bf35/378235970/instance/2025-08-12_0ffa0484b8309.jpg",
    "totalPlays": 0,
    "publishedYear": 2015,
    "subtitle": "7 원더스 대결",
    "bggUrl": "https://boardgamegeek.com/boardgame/173346",
    "duration": "30",
  },
  {
    "id": "266192",
    "title": "Wingspan",
    "players": "1-5",
    "playTime": "40-70",
    "weight": 2.5,
    "imageUrl": "https://orionmagazine.org/wp-content/uploads/2023/11/faith-wingspan2-1400x1050.jpg",
    "totalPlays": 0,
    "publishedYear": 2019,
    "subtitle": "윙스팬",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/266192",
    "duration": "40-70",
  },
  {
    "id": "124361",
    "title": "Concordia",
    "players": "2-5",
    "playTime": "90",
    "weight": 3,
    "imageUrl": "https://cf.geekdo-images.com/CzwSm8i7tkLz6cBnrILZBg__itemrep@2x/img/sJH1s7kSr1kU35nkAXoBhGTTZ0A=/fit-in/492x600/filters:strip_icc()/pic3453267.jpg",
    "totalPlays": 0,
    "publishedYear": 2013,
    "subtitle": "콩코르디아",
    "bggUrl": "https://boardgamegeek.com/boardgame/124361",
    "duration": "90",
  },
  {
    "id": "237182",
    "title": "Root",
    "players": "2-4",
    "playTime": "60-90",
    "weight": 3.8,
    "imageUrl": "https://accidentallycoolgames.com/cdn/shop/products/91E7bCmI2HL._AC_SL1500_800x.png?v=1678807108",
    "totalPlays": 0,
    "publishedYear": 2018,
    "subtitle": "루트",
    "status": "Wishlist",
    "bggUrl": "https://boardgamegeek.com/boardgame/237182",
    "duration": "60-90",
  },
  {
    "id": "193738",
    "title": "Great Western Trail",
    "players": "2-4",
    "playTime": "75-150",
    "weight": 3.7,
    "imageUrl": "https://cf.geekdo-images.com/gDn7AhrDlmfCLSz9ZqoNFQ__itemrep/img/0FOms0QcPYvwEMWVXsy9p0FjGlM=/fit-in/246x300/filters:strip_icc()/pic5988511.jpg",
    "totalPlays": 1,
    "publishedYear": 2016,
    "subtitle": "그레이트웨스턴트레일",
    "bggUrl": "https://boardgamegeek.com/boardgame/193738",
    "duration": "75-150",
  },
  {
    "id": "164928",
    "title": "Orléans: Big Box",
    "players": "2-5",
    "playTime": "90",
    "weight": 3,
    "imageUrl": "https://www.thegamesteward.com/cdn/shop/products/orleans-deluxe-edition-kickstarter-special-kickstarter-board-game-tasty-minstrel-games-34726879035544.png?v=1634372506&width=1141",
    "totalPlays": 2,
    "publishedYear": 2014,
    "subtitle": "오를레앙 빅박스",
    "status": "Owned",
    "bggUrl": "https://boardgamegeek.com/boardgame/164928",
    "duration": "90",
  },
  {
    "id": "96848",
    "title": "Mage Knight Board Game",
    "players": "1-4",
    "playTime": "60-240",
    "weight": 4.4,
    "imageUrl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEioMXqT93nVeZK4EOzXFVjbeUTzPM5tqWIRdvYWPy50zz5Hb610QQtNJpg5LZDoIr-1CmK4t8D5BibHKAskjLXHVbhpHEis8LzVxhWl5bukKyYBwYWTCWH4TrcQ1g5s8QmxILk6v8qtLqs/s1600/DSC04589.JPG",
    "totalPlays": 0,
    "publishedYear": 2011,
    "subtitle": "메이지 나이트",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/96848",
    "duration": "60-240",
  },
  {
    "id": "284083",
    "title": "The Crew: The Quest for Planet Nine",
    "players": "2-5",
    "playTime": "20",
    "weight": 2,
    "imageUrl": "https://www.thegamesteward.com/cdn/shop/products/the-crew-the-quest-for-planet-nine-retail-edition-retail-board-game-kosmos-34732948226200.jpg?v=1634380251&width=1790",
    "totalPlays": 0,
    "publishedYear": 2019,
    "subtitle": "스페이스 크루",
    "bggUrl": "https://boardgamegeek.com/boardgame/284083",
    "duration": "20",
  },
  {
    "id": "126163",
    "title": "Tzolk'in: The Mayan Calendar",
    "players": "2-4",
    "playTime": "90",
    "weight": 3.7,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPRue5PeQ2GRiDbOJnug6lZos1BN_eEpObsA&s",
    "totalPlays": 0,
    "publishedYear": 2012,
    "subtitle": "촐킨: 마야의 달력",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/126163",
    "duration": "90",
  },
  {
    "id": "266507",
    "title": "Clank! Legacy: Acquisitions Incorporated",
    "players": "2-4",
    "playTime": "90-120",
    "weight": 2.7,
    "imageUrl": "https://cannibalhalflinggaming.com/wp-content/uploads/2019/04/acqinc-e1554665305382.jpg?w=672&h=372&crop=1",
    "totalPlays": 0,
    "publishedYear": 2019,
    "subtitle": "클랭크! 레거시: 전리품 주식회사",
    "status": "Wishlist",
    "bggUrl": "https://boardgamegeek.com/boardgame/266507",
    "duration": "90-120",
  },
  {
    "id": "230802",
    "title": "Azul",
    "players": "2-4",
    "playTime": "30-45",
    "weight": 1.8,
    "imageUrl": "https://www.artofplay.com/cdn/shop/products/azul-gameboard_4bd62a84-3da9-4a72-9189-4a124a58d271.png?v=1636415879&width=1024",
    "totalPlays": 0,
    "publishedYear": 2017,
    "subtitle": "아줄",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/230802",
    "duration": "30-45",
  },
  {
    "id": "183394",
    "title": "Viticulture Essential Edition",
    "players": "1-6",
    "playTime": "45-90",
    "weight": 2.9,
    "imageUrl": "https://tabletopmerchant.com/cdn/shop/files/ViticultureGameplay6_800x.jpg?v=1736975384",
    "totalPlays": 0,
    "publishedYear": 2015,
    "subtitle": "비티컬처 에센셜 에디션",
    "bggUrl": "https://boardgamegeek.com/boardgame/183394",
    "duration": "45-90",
  },
  {
    "id": "244521",
    "title": "The Quacks of Quedlinburg",
    "players": "2-4",
    "playTime": "45",
    "weight": 1.9,
    "imageUrl": "https://cf.geekdo-images.com/wQSn7A0X-EblZPjUqvfwmQ__imagepage/img/37svyD2v0FhduCTTMDAVav8arJo=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3942497.png",
    "totalPlays": 0,
    "publishedYear": 2018,
    "subtitle": "크베들린부르크의 돌팔이 약장수",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/244521",
    "duration": "45",
  },
  {
    "id": "13",
    "title": "Catan",
    "players": "3-4",
    "playTime": "60-120",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/_GqBbXEWUuSHr9E2eSZNSw__imagepage/img/PDNKg3lHfE5A1N-2Z0jLCG5qpjk=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2730.jpg",
    "totalPlays": 0,
    "publishedYear": 1995,
    "subtitle": "카탄의 개척자",
    "bggUrl": "https://boardgamegeek.com/boardgame/13",
    "duration": "60-120",
  },
  {
    "id": "9209",
    "title": "Ticket to Ride",
    "players": "2-5",
    "playTime": "30-60",
    "weight": 1.8,
    "imageUrl": "https://www.autostraddle.com/wp-content/uploads/2013/01/photo-31.jpeg?fit=1352,924",
    "totalPlays": 0,
    "publishedYear": 2004,
    "subtitle": "티켓 투 라이드",
    "bggUrl": "https://boardgamegeek.com/boardgame/9209",
    "duration": "30-60",
  },
  {
    "id": "822",
    "title": "Carcassonne",
    "players": "2-5",
    "playTime": "30-45",
    "weight": 1.9,
    "imageUrl": "https://media.karousell.com/media/photos/products/2024/6/19/carcassonne_chinese_editions_1718764175_28691dc7_progressive.jpg",
    "totalPlays": 0,
    "publishedYear": 2000,
    "subtitle": "카르카손",
    "bggUrl": "https://boardgamegeek.com/boardgame/822",
    "duration": "30-45",
  },
  {
    "id": "148228",
    "title": "Splendor",
    "players": "2-4",
    "playTime": "30",
    "weight": 1.8,
    "imageUrl": "https://cf.geekdo-images.com/vNFe4JkhKAERzi4T0Ntwpw__itemrep@2x/img/qDjpnPQ6u7oROPU9dS3c_opVIFc=/fit-in/492x600/filters:strip_icc()/pic8234167.png",
    "totalPlays": 0,
    "publishedYear": 2014,
    "subtitle": "스플렌더",
    "bggUrl": "https://boardgamegeek.com/boardgame/148228",
    "duration": "30",
  },
  {
    "id": "163412",
    "title": "Patchwork",
    "players": "2",
    "playTime": "15-30",
    "weight": 1.6,
    "imageUrl": "https://meeplelikeus.b-cdn.net/wp-content/uploads/2016/05/20160514_135822.jpg",
    "totalPlays": 0,
    "publishedYear": 2014,
    "subtitle": "패치워크",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/163412",
    "duration": "15-30",
  },
  {
    "id": "36218",
    "title": "Dominion",
    "players": "2-4",
    "playTime": "30",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/j6iQpZ4XkemZP07HNCODBA__itemrep@2x/img/6pTUe8e0xuNPTFgNMYabr7zg4ks=/fit-in/492x600/filters:strip_icc()/pic394356.jpg",
    "totalPlays": 0,
    "publishedYear": 2008,
    "subtitle": "도미니언",
    "bggUrl": "https://boardgamegeek.com/boardgame/36218",
    "duration": "30",
  },
  {
    "id": "68448",
    "title": "7 Wonders",
    "players": "2-7",
    "playTime": "30",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/35h9Za_JvMMMtx_92kT0Jg__itemrep@2x/img/C1Q2lgN2URAqsAtanK5XI72phN8=/fit-in/492x600/filters:strip_icc()/pic7149798.jpg",
    "totalPlays": 0,
    "publishedYear": 2010,
    "subtitle": "7 원더스",
    "bggUrl": "https://boardgamegeek.com/boardgame/68448",
    "duration": "30",
  },
  {
    "id": "31260",
    "title": "Agricola",
    "players": "1-5",
    "playTime": "30-150",
    "weight": 3.6,
    "imageUrl": "https://cf.geekdo-images.com/3L6ZtOll9W5O6-3-EwSMyw__itemrep/img/8VVXhLllK6HGLr406rykMMFimUQ=/fit-in/246x300/filters:strip_icc()/pic1899157.jpg",
    "totalPlays": 0,
    "publishedYear": 2007,
    "subtitle": "아그리콜라",
    "bggUrl": "https://boardgamegeek.com/boardgame/31260",
    "duration": "30-150",
  },
  {
    "id": "28143",
    "title": "Race for the Galaxy",
    "players": "2-4",
    "playTime": "30-60",
    "weight": 3,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/en/1/1c/Rftg_cover.jpg",
    "totalPlays": 1,
    "publishedYear": 2007,
    "subtitle": "레이스 포 더 갤럭시",
    "bggUrl": "https://boardgamegeek.com/boardgame/28143",
    "duration": "30-60",
  },
  {
    "id": "3076",
    "title": "Puerto Rico",
    "players": "3-5",
    "playTime": "90-150",
    "weight": 3.3,
    "imageUrl": "https://cf.geekdo-images.com/QFiIRd2kimaMqTyWsX0aUg__itemrep/img/YDEozo5DfKYdDp8xi2mAfoV2qWk=/fit-in/246x300/filters:strip_icc()/pic158548.jpg",
    "totalPlays": 0,
    "publishedYear": 2002,
    "subtitle": "푸에르토리코",
    "bggUrl": "https://boardgamegeek.com/boardgame/3076",
    "duration": "90-150",
  },
  {
    "id": "2651",
    "title": "Power Grid",
    "players": "2-6",
    "playTime": "120",
    "weight": 3.2,
    "imageUrl": "https://cf.geekdo-images.com/yd6LuatytHRhcFCxCf-EEg__itemrep/img/LsqKzcnoaVUlSUmLxFE8dwxFndk=/fit-in/246x300/filters:strip_icc()/pic4459753.jpg",
    "totalPlays": 0,
    "publishedYear": 2004,
    "subtitle": "파워 그리드",
    "bggUrl": "https://boardgamegeek.com/boardgame/2651",
    "duration": "120",
  },
  {
    "id": "171908",
    "title": "El Grande Big Box",
    "players": "2-5",
    "playTime": "60-120",
    "weight": 2.8,
    "imageUrl": "https://cf.geekdo-images.com/dTREkApZZA0e46TYFmVgIA__itemrep/img/q19AU5EyVIT7VNO6lDwrt6x-Kdg=/fit-in/246x300/filters:strip_icc()/pic2748424.jpg",
    "totalPlays": 1,
    "publishedYear": 2015,
    "subtitle": "엘 그란데 빅 박스",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/171908",
    "duration": "60-120",
  },
  {
    "id": "397598",
    "title": "Dune: Imperium – Uprising",
    "players": "1-6",
    "playTime": "60-120",
    "weight": 3.5,
    "imageUrl": "https://cf.geekdo-images.com/UVUkjMV_Q2paVUIUP30Vvw__itemrep/img/ZQPDp9gumb19lmgdAvNMf5XN_c0=/fit-in/246x300/filters:strip_icc()/pic7664424.jpg",
    "totalPlays": 0,
    "publishedYear": 2023,
    "subtitle": "듄: 임페리움",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/397598",
    "duration": "60-120",
  },
  {
    "id": "43015",
    "title": "Hansa Teutonica",
    "players": "2-5",
    "playTime": "45-90",
    "weight": 3.1,
    "imageUrl": "https://juegosdelamesaredonda.com/18475-large_default/hansa-teutonica-new-edition-english.jpg",
    "totalPlays": 0,
    "publishedYear": 2009,
    "subtitle": "한자 토이토니카",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/43015",
    "duration": "45-90",
  },
  {
    "id": "12",
    "title": "Ra",
    "players": "2-5",
    "playTime": "45-60",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/k7lG683LBZdvFyS-FH-MpA__opengraph/img/UrxC7YZkJ2pyWgBfLIIGp8DWj-I=/0x49:1423x796/fit-in/1200x630/filters:strip_icc()/pic6746812.png",
    "totalPlays": 0,
    "publishedYear": 1999,
    "subtitle": "태양신 라",
    "status": "Preorder",
    "bggUrl": "https://boardgamegeek.com/boardgame/12",
    "duration": "45-60",
  },
  {
    "id": "128882",
    "title": "The Resistance: Avalon",
    "players": "5-10",
    "playTime": "30",
    "weight": 1.7,
    "imageUrl": "https://cf.geekdo-images.com/LPa6rsGcv8S0-OeNjCOAEQ__itemrep/img/KtGX_JFWNUXci7H5zs7GjS0QrQk=/fit-in/246x300/filters:strip_icc()/pic1398895.jpg",
    "totalPlays": 0,
    "publishedYear": 2012,
    "subtitle": "레지스탕스: 아발론",
    "bggUrl": "https://boardgamegeek.com/boardgame/128882",
    "duration": "30",
  },
  {
    "id": "34635",
    "title": "Stone Age",
    "players": "2-4",
    "playTime": "60-90",
    "weight": 2.5,
    "imageUrl": "https://cf.geekdo-images.com/elmZegVZ6gp4_5izUgxGQQ__itemrep/img/vApiI-gvXtwafEriPc4jDVJ1ajA=/fit-in/246x300/filters:strip_icc()/pic1632539.jpg",
    "totalPlays": 0,
    "publishedYear": 2008,
    "subtitle": "석기시대",
    "bggUrl": "https://boardgamegeek.com/boardgame/34635",
    "duration": "60-90",
  },
  {
    "id": "274364",
    "title": "Watergate",
    "players": "2",
    "playTime": "30-60",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/iTBogxNFa3Ymh-6ST3srsw__itemrep/img/MJILkAufstnOuPV6rrccZ8vuoxw=/fit-in/246x300/filters:strip_icc()/pic4768766.jpg",
    "totalPlays": 0,
    "publishedYear": 2019,
    "subtitle": "워터게이트",
    "bggUrl": "https://boardgamegeek.com/boardgame/274364",
    "duration": "30-60",
  },
  {
    "id": "118048",
    "title": "Targi",
    "players": "2",
    "playTime": "60",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/wHg4fOf48cs1kw1PDOk1tQ__itemrep@2x/img/qhzcnDQsQCZ6cV__mDioebCjWac=/fit-in/492x600/filters:strip_icc()/pic3958793.jpg",
    "totalPlays": 0,
    "publishedYear": 2012,
    "subtitle": "타르기",
    "bggUrl": "https://boardgamegeek.com/boardgame/118048",
    "duration": "60",
  },
  {
    "id": "157354",
    "title": "Five Tribes: The Djinns of Naqala",
    "players": "2-4",
    "playTime": "40-80",
    "weight": 2.8,
    "imageUrl": "https://cf.geekdo-images.com/dmo-WD6HZHVUPrbVHunaTw__itemrep@2x/img/zuzTFDhvV2L8IAtxo0XAcB5kq-w=/fit-in/492x600/filters:strip_icc()/pic2055255.jpg",
    "totalPlays": 0,
    "publishedYear": 2014,
    "subtitle": "다섯 부족: 나칼라의 정령들",
    "bggUrl": "https://boardgamegeek.com/boardgame/157354",
    "duration": "40-80",
  },
  {
    "id": "73439",
    "title": "Troyes",
    "players": "1-4",
    "playTime": "90",
    "weight": 3.4,
    "imageUrl": "https://cf.geekdo-images.com/fBIe-aEPtJKC-ceNlspK6A__itemrep/img/nGkHMvIQV9bPY8RmVt7NigJwNOM=/fit-in/246x300/filters:strip_icc()/pic750583.jpg",
    "totalPlays": 0,
    "publishedYear": 2010,
    "subtitle": "트루아",
    "bggUrl": "https://boardgamegeek.com/boardgame/73439",
    "duration": "90",
  },
  {
    "id": "251247",
    "title": "Barrage",
    "players": "1-4",
    "playTime": "60-120",
    "weight": 4.1,
    "imageUrl": "https://cf.geekdo-images.com/jEPmWvvYpqkWrKOzqIHFsg__itemrep@2x/img/aS773dDJTpgmO9UxQF-emlZpBeI=/fit-in/492x600/filters:strip_icc()/pic4336469.png",
    "totalPlays": 0,
    "publishedYear": 2019,
    "subtitle": "버라��",
    "bggUrl": "https://boardgamegeek.com/boardgame/251247",
    "duration": "60-120",
  },
  {
    "id": "30549",
    "title": "Pandemic",
    "players": "2-4",
    "playTime": "45",
    "weight": 2.4,
    "imageUrl": "https://i.ebayimg.com/images/g/NwsAAeSw~DNpZnBT/s-l1200.webp",
    "totalPlays": 0,
    "publishedYear": 2008,
    "subtitle": "팬데믹",
    "bggUrl": "https://boardgamegeek.com/boardgame/30549",
    "duration": "45",
  },
  {
    "id": "293014",
    "title": "Nidavellir",
    "players": "2-5",
    "playTime": "45",
    "weight": 2.1,
    "imageUrl": "https://cf.geekdo-images.com/PX7t5xXDLI2XqxoTShLayg__itemrep/img/-2DjDG1x3IfG1mAu-xACSDSfWfw=/fit-in/246x300/filters:strip_icc()/pic5039625.jpg",
    "totalPlays": 0,
    "publishedYear": 2020,
    "subtitle": "니다벨리르",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/293014",
    "duration": "45",
  },
  {
    "id": "262712",
    "title": "Res Arcana",
    "players": "2-4",
    "playTime": "30-60",
    "weight": 2.7,
    "imageUrl": "https://spacebiff.com/wp-content/uploads/2019/05/3.-synerdragons.jpg?w=604&h=239",
    "totalPlays": 0,
    "publishedYear": 2019,
    "subtitle": "레즈 아르카나",
    "bggUrl": "https://boardgamegeek.com/boardgame/262712",
    "duration": "30-60",
  },
  {
    "id": "271324",
    "title": "It's a Wonderful World",
    "players": "1-5",
    "playTime": "30-60",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/od4vDTdXGPSVc-kjLqM11w__itemrep@2x/img/8FpWzkugXPnjGHeMnsvh7IJHBEE=/fit-in/492x600/filters:strip_icc()/pic4651175.jpg",
    "totalPlays": 2,
    "publishedYear": 2019,
    "subtitle": "원더풀 월드",
    "status": "Owned",
    "bggUrl": "https://boardgamegeek.com/boardgame/271324",
    "duration": "30-60",
  },
  {
    "id": "263918",
    "title": "Cartographers",
    "players": "1-100",
    "playTime": "30-45",
    "weight": 1.9,
    "imageUrl": "https://cf.geekdo-images.com/GifbnAmsA4lfEcDkeaC9VA__itemrep@2x/img/OJIP09uX080q21zF2Oz0ViZER64=/fit-in/492x600/filters:strip_icc()/pic4397932.png",
    "totalPlays": 3,
    "publishedYear": 2019,
    "subtitle": "지도 제작자들",
    "bggUrl": "https://boardgamegeek.com/boardgame/263918",
    "duration": "30-45",
  },
  {
    "id": "279537",
    "title": "The Search for Planet X",
    "players": "1-4",
    "playTime": "60-75",
    "weight": 2.4,
    "imageUrl": "https://cf.geekdo-images.com/NItjtztEUAKOpaTWZddu9A__itemrep@2x/img/7oi5XRLpf7AMj8SgYuFmsgdBqoQ=/fit-in/492x600/filters:strip_icc()/pic5744928.jpg",
    "totalPlays": 6,
    "publishedYear": 2020,
    "subtitle": "행성 X를 찾아서",
    "bggUrl": "https://boardgamegeek.com/boardgame/279537",
    "duration": "60-75",
  },
  {
    "id": "35677",
    "title": "Le Havre",
    "players": "1-5",
    "playTime": "100-200",
    "weight": 3.7,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/en/3/3e/Le_Havre_game.jpg",
    "totalPlays": 1,
    "publishedYear": 2008,
    "subtitle": "르아브르",
    "bggUrl": "https://boardgamegeek.com/boardgame/35677",
    "duration": "100-200",
  },
  {
    "id": "102794",
    "title": "Caverna: The Cave Farmers",
    "players": "1-7",
    "playTime": "30-210",
    "weight": 3.8,
    "imageUrl": "https://cf.geekdo-images.com/EAqbd46lFxo-7GumlO8U4w__itemrep@2x/img/UgRRkcfmBNo-Qjctpp7HVegtNUc=/fit-in/492x600/filters:strip_icc()/pic5598833.jpg",
    "totalPlays": 0,
    "publishedYear": 2013,
    "subtitle": "카베르나: 동굴 속 농부들",
    "bggUrl": "https://boardgamegeek.com/boardgame/102794",
    "duration": "30-210",
  },
  {
    "id": "171",
    "title": "Chess",
    "players": "2",
    "playTime": "60",
    "weight": 3.6,
    "imageUrl": "https://www.sklep-szachy.pl/1471-large_default/chess-checkers-l.jpg",
    "totalPlays": 1,
    "publishedYear": 1475,
    "subtitle": "체스",
    "bggUrl": "https://boardgamegeek.com/boardgame/171",
    "duration": "60",
  },
  {
    "id": "2093",
    "title": "Mahjong",
    "players": "3-4",
    "playTime": "120",
    "weight": 2.6,
    "imageUrl": "https://mahjqueen.com/cdn/shop/files/NeonDaze.jpg?v=1767207378&width=1946",
    "totalPlays": 0,
    "publishedYear": 1850,
    "subtitle": "마작",
    "bggUrl": "https://boardgamegeek.com/boardgame/2093",
    "duration": "120",
  },
  {
    "id": "47",
    "title": "Chinatown",
    "players": "3-5",
    "playTime": "60",
    "weight": 2.2,
    "imageUrl": "https://cf.geekdo-images.com/o23NBqu_LBRAtRaVoOBBhQ__itemrep/img/6jfMOOOD7EDARl4LMwP4aTZdaC4=/fit-in/246x300/filters:strip_icc()/pic403442.jpg",
    "totalPlays": 0,
    "publishedYear": 1999,
    "subtitle": "차이나타운",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/47",
    "duration": "60",
  },
  {
    "id": "118",
    "title": "Modern Art",
    "players": "3-5",
    "playTime": "45-60",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/wLto-xaabHwKQe_Bc4iD1Q__itemrep/img/50m6JYV9RIt0kXps9f100ockzHU=/fit-in/246x300/filters:strip_icc()/pic3458036.png",
    "totalPlays": 0,
    "publishedYear": 1992,
    "subtitle": "모던아트",
    "bggUrl": "https://boardgamegeek.com/boardgame/118",
    "duration": "45-60",
  },
  {
    "id": "365258",
    "title": "World Wonders",
    "players": "1-5",
    "playTime": "50-70",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/GGi5aUL1dVQIrytxgXow4g__itemrep/img/cuDfJpNjCJQrNjJ4CL80U4u72B4=/fit-in/246x300/filters:strip_icc()/pic7604558.png",
    "totalPlays": 1,
    "publishedYear": 2023,
    "subtitle": "월드 원더스",
    "bggUrl": "https://boardgamegeek.com/boardgame/365258",
    "duration": "50-70",
  },
  {
    "id": "359318",
    "title": "Foxy",
    "players": "1-5",
    "playTime": "15-20",
    "weight": 1,
    "imageUrl": "https://cf.geekdo-images.com/XDpdEXoQ69LpEHorqlaWFw__itemrep/img/5PHQFyoE7_mRjRB6VBHMpNTjcuU=/fit-in/246x300/filters:strip_icc()/pic9149091.jpg",
    "totalPlays": 0,
    "publishedYear": 2022,
    "subtitle": "폭시",
    "bggUrl": "https://boardgamegeek.com/boardgame/359318",
    "duration": "15-20",
  },
  {
    "id": "117959",
    "title": "Las Vegas",
    "players": "2-5",
    "playTime": "30",
    "weight": 1.2,
    "imageUrl": "https://cf.geekdo-images.com/aQJ0HRKx2mobP0g3FCeR_Q__itemrep@2x/img/9jed8PbaZus3Ba5UWVkqv2zp6bI=/fit-in/492x600/filters:strip_icc()/pic1261796.jpg",
    "totalPlays": 0,
    "publishedYear": 2012,
    "subtitle": "라스베가스",
    "bggUrl": "https://boardgamegeek.com/boardgame/117959",
    "duration": "30",
  },
  {
    "id": "929",
    "title": "The Great Dalmuti",
    "players": "4-8",
    "playTime": "15-60",
    "weight": 1.3,
    "imageUrl": "https://cf.geekdo-images.com/LVCXyZpkL6rPsouhWV3noA__itemrep@2x/img/shGjUhsgU-b9g3yo2iV54FwSkrE=/fit-in/492x600/filters:strip_icc()/pic711236.jpg",
    "totalPlays": 0,
    "publishedYear": 1995,
    "subtitle": "위대한 달무티",
    "bggUrl": "https://boardgamegeek.com/boardgame/929",
    "duration": "15-60",
  },
  {
    "id": "9220",
    "title": "Saboteur",
    "players": "3-10",
    "playTime": "30",
    "weight": 1.3,
    "imageUrl": "https://cf.geekdo-images.com/0vJwP6NGa7GHPZKC3gplUw__itemrep/img/aJcXGhYr8XxyKEK6EqbG0bePrOk=/fit-in/246x300/filters:strip_icc()/pic3989824.jpg",
    "totalPlays": 0,
    "publishedYear": 2004,
    "subtitle": "사보타지",
    "bggUrl": "https://boardgamegeek.com/boardgame/9220",
    "duration": "30",
  },
  {
    "id": "29223",
    "title": "Marrakech",
    "players": "2-4",
    "playTime": "30",
    "weight": 1.3,
    "imageUrl": "https://cf.geekdo-images.com/JFE29MODWOFXreEmM-xhyQ__itemrep@2x/img/yWxHy85jYDT4v98CK6z3tsYNgrg=/fit-in/492x600/filters:strip_icc()/pic8594649.jpg",
    "totalPlays": 0,
    "publishedYear": 2007,
    "subtitle": "마라케시",
    "bggUrl": "https://boardgamegeek.com/boardgame/29223",
    "duration": "30",
  },
  {
    "id": "147151",
    "title": "Concept",
    "players": "4-12",
    "playTime": "40",
    "weight": 1.4,
    "imageUrl": "https://cf.geekdo-images.com/hHFs0_KRoW_FJ0cMIVgZcw__itemrep@2x/img/6i08rmiKBfgz9cGOBqH7WxVU35s=/fit-in/492x600/filters:strip_icc()/pic4991925.jpg",
    "totalPlays": 0,
    "publishedYear": 2013,
    "subtitle": "콘셉트",
    "bggUrl": "https://boardgamegeek.com/boardgame/147151",
    "duration": "40",
  },
  {
    "id": "131357",
    "title": "Coup",
    "players": "2-6",
    "playTime": "15",
    "weight": 1.4,
    "imageUrl": "https://cf.geekdo-images.com/MWhSY_GOe2-bmlQ2rntSVg__itemrep/img/QRw3T5XGsrRs-QKCSpzwE7nFqOg=/fit-in/246x300/filters:strip_icc()/pic2016054.jpg",
    "totalPlays": 0,
    "publishedYear": 2012,
    "subtitle": "쿠",
    "bggUrl": "https://boardgamegeek.com/boardgame/131357",
    "duration": "15",
  },
  {
    "id": "243430",
    "title": "Krass Kariert",
    "players": "3-5",
    "playTime": "30",
    "weight": 1.4,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBFVLM3ejGtqO8ZMVZm9aVhH3FQ3gB1RDH1w&s",
    "totalPlays": 0,
    "subtitle": "크라스 카리어트",
    "bggUrl": "https://boardgamegeek.com/boardgame/243430",
    "duration": "30",
    "publishedYear": 2018,
  },
  {
    "id": "260605",
    "title": "Camel Up 2nd",
    "players": "3-8",
    "playTime": "30-45",
    "weight": 1.5,
    "imageUrl": "https://cf.geekdo-images.com/qnR2V3YsW963_JaVznBjsw__itemrep@2x/img/V7DdqZ6UqzwaCEc_3BVkvdlylh8=/fit-in/492x600/filters:strip_icc()/pic8584959.jpg",
    "totalPlays": 0,
    "publishedYear": 2018,
    "subtitle": "카멜업",
    "bggUrl": "https://boardgamegeek.com/boardgame/260605",
    "duration": "30-45",
  },
  {
    "id": "260180",
    "title": "Project L",
    "players": "1-4",
    "playTime": "20-40",
    "weight": 1.6,
    "imageUrl": "https://cf.geekdo-images.com/Zwx2ZXS6r6PaxhkaVEe75Q__itemrep@2x/img/9MO2l8uhGDoUdzEl7c28UB0t06g=/fit-in/492x600/filters:strip_icc()/pic4309147.jpg",
    "totalPlays": 0,
    "publishedYear": 2020,
    "subtitle": "프로젝트 L",
    "bggUrl": "https://boardgamegeek.com/boardgame/260180",
    "duration": "20-40",
  },
  {
    "id": "3955",
    "title": "Bang!",
    "players": "4-7",
    "playTime": "20-40",
    "weight": 1.6,
    "imageUrl": "https://cf.geekdo-images.com/_04xA-d-rfygm0c49HE4vA__itemrep@2x/img/y8voqbS1PSXTwdM-hIhQYDNACls=/fit-in/492x600/filters:strip_icc()/pic1170986.jpg",
    "totalPlays": 0,
    "publishedYear": 2002,
    "subtitle": "뱅!",
    "bggUrl": "https://boardgamegeek.com/boardgame/3955",
    "duration": "20-40",
  },
  {
    "id": "11",
    "title": "Bohnanza",
    "players": "2-7",
    "playTime": "45",
    "weight": 1.7,
    "imageUrl": "https://cf.geekdo-images.com/8SADtu_4zBH_UJrCo935Iw__itemrep@2x/img/xAF8FdMtv2Zz2kbhgKEWv-AxA6s=/fit-in/492x600/filters:strip_icc()/pic6348964.jpg",
    "totalPlays": 0,
    "publishedYear": 1997,
    "subtitle": "보난자",
    "bggUrl": "https://boardgamegeek.com/boardgame/11",
    "duration": "45",
  },
  {
    "id": "271693",
    "title": "River Flow",
    "players": "1-4",
    "playTime": "20",
    "weight": 1.6,
    "imageUrl": "https://cf.geekdo-images.com/iEQ2T_Ipv3vx2aN3O9JzIQ__itemrep@2x/img/6OmHQ5QpvyJUVOLwrovTD3C0ckA=/fit-in/492x600/filters:strip_icc()/pic4572645.jpg",
    "totalPlays": 0,
    "publishedYear": 2019,
    "subtitle": "리버 플로우",
    "bggUrl": "https://boardgamegeek.com/boardgame/271693",
    "duration": "20",
  },
  {
    "id": "423517",
    "title": "3 Chapters",
    "players": "2-6",
    "playTime": "30",
    "weight": 1.7,
    "imageUrl": "https://cf.geekdo-images.com/es3F2drfUOIVnqsTds3BDQ__itemrep@2x/img/Qft9La9Wtz54bF0UR8PYIXJ-dWY=/fit-in/492x600/filters:strip_icc()/pic8940639.png",
    "totalPlays": 1,
    "publishedYear": 2024,
    "subtitle": "세 번째 이야기",
    "bggUrl": "https://boardgamegeek.com/boardgame/423517",
    "duration": "30",
  },
  {
    "id": "232832",
    "title": "Century: Golem Edition",
    "players": "2-5",
    "playTime": "30-45",
    "weight": 1.7,
    "imageUrl": "https://cf.geekdo-images.com/1bihoShOuqaCuZJXB3Q2gQ__itemrep@2x/img/sp3v24SR4tSru02vcXQsRYO9U2A=/fit-in/492x600/filters:strip_icc()/pic3936124.jpg",
    "totalPlays": 0,
    "publishedYear": 2017,
    "subtitle": "센추리: 골렘 에디션",
    "bggUrl": "https://boardgamegeek.com/boardgame/232832",
    "duration": "30-45",
  },
  {
    "id": "1465",
    "title": "Wizard",
    "players": "3-6",
    "playTime": "45",
    "weight": 1.7,
    "imageUrl": "https://cf.geekdo-images.com/ygVQlepjPxyg7IizSCM_Tw__itemrep/img/-B_jX6C9fieqybdOUVcGWA1-zck=/fit-in/246x300/filters:strip_icc()/pic5948.jpg",
    "totalPlays": 0,
    "publishedYear": 1984,
    "subtitle": "위자드",
    "bggUrl": "https://boardgamegeek.com/boardgame/1465",
    "duration": "45",
  },
  {
    "id": "25196",
    "title": "Rummikub Six Player",
    "players": "2-6",
    "playTime": "60",
    "weight": 1,
    "imageUrl": "https://cf.geekdo-images.com/FDeTekGBQrBi3fA0P9vTQQ__itemrep/img/KoY8bFgmxKqGs_w4VA5TyE4nVJA=/fit-in/246x300/filters:strip_icc()/pic143010.jpg",
    "totalPlays": 0,
    "publishedYear": 1992,
    "subtitle": "루미큐브",
    "bggUrl": "https://boardgamegeek.com/boardgame/25196",
    "duration": "60",
  },
  {
    "id": "230080",
    "title": "Majesty: For the Realm",
    "players": "2-4",
    "playTime": "20-30",
    "weight": 1.7,
    "imageUrl": "https://cf.geekdo-images.com/BsNE-w6bttGZ-JPLcY95mA__itemrep@2x/img/iLMxcEBuqtyMBNfTLlr2cRtGjDY=/fit-in/492x600/filters:strip_icc()/pic3742410.jpg",
    "totalPlays": 0,
    "publishedYear": 2017,
    "subtitle": "마제스티",
    "bggUrl": "https://boardgamegeek.com/boardgame/230080",
    "duration": "20-30",
  },
  {
    "id": "150145",
    "title": "Skull King",
    "players": "2-8",
    "playTime": "30",
    "weight": 1.7,
    "imageUrl": "https://cf.geekdo-images.com/1qvA21HdRaPYwrn4tGDNaQ__itemrep@2x/img/u282aOGplMokEqS8ID7MuYwjnNs=/fit-in/492x600/filters:strip_icc()/pic8689185.jpg",
    "totalPlays": 0,
    "publishedYear": 2013,
    "subtitle": "스컬킹",
    "bggUrl": "https://boardgamegeek.com/boardgame/150145",
    "duration": "30",
  },
  {
    "id": "65244",
    "title": "Forbidden Island",
    "players": "2-4",
    "playTime": "30",
    "weight": 1.7,
    "imageUrl": "https://cf.geekdo-images.com/JgAkEBUaiHOsOS94iRMs2w__itemrep@2x/img/WZqvQguwQfQgUPUnrsj2gOqhfOI=/fit-in/492x600/filters:strip_icc()/pic646458.jpg",
    "totalPlays": 0,
    "publishedYear": 2010,
    "subtitle": "포비든 아일랜드",
    "bggUrl": "https://boardgamegeek.com/boardgame/65244",
    "duration": "30",
  },
  {
    "id": "102835",
    "title": "Lost Temple",
    "players": "2-8",
    "playTime": "40",
    "weight": 1.7,
    "imageUrl": "https://cf.geekdo-images.com/YNxToYNXkHIehCztt96sRA__itemrep/img/d3ntTZRwdlz42YHqNYqShOCQ4F4=/fit-in/246x300/filters:strip_icc()/pic1045956.jpg",
    "totalPlays": 0,
    "publishedYear": 2011,
    "subtitle": "로스트 템플",
    "bggUrl": "https://boardgamegeek.com/boardgame/102835",
    "duration": "40",
  },
  {
    "id": "37380",
    "title": "Roll Through the Ages: The Bronze Age",
    "players": "1-4",
    "playTime": "35",
    "weight": 1.8,
    "imageUrl": "https://cf.geekdo-images.com/VoLyy7ScO6aAU9Neo7KCiA__itemrep@2x/img/c6x2OMvWfOjLbTOYvSwz8kPkoh0=/fit-in/492x600/filters:strip_icc()/pic986758.jpg",
    "totalPlays": 0,
    "publishedYear": 2008,
    "subtitle": "롤 쓰루 디 에이지스: 청동기 시대",
    "bggUrl": "https://boardgamegeek.com/boardgame/37380",
    "duration": "35",
  },
  {
    "id": "377061",
    "title": "Coffee Rush",
    "players": "2-4",
    "playTime": "30",
    "weight": 1.8,
    "imageUrl": "https://cf.geekdo-images.com/LdK5ItPPwIHKUITxh3vqxA__itemrep@2x/img/QqAIm9UFLNJXbf3L50-3kWnNpRU=/fit-in/492x600/filters:strip_icc()/pic7275386.jpg",
    "totalPlays": 0,
    "publishedYear": 2023,
    "subtitle": "커피 러시",
    "bggUrl": "https://boardgamegeek.com/boardgame/377061",
    "duration": "30",
    "status": "Owned",
  },
  {
    "id": "357563",
    "title": "Akropolis",
    "players": "1-4",
    "playTime": "20-30",
    "weight": 1.8,
    "imageUrl": "https://cf.geekdo-images.com/OTb0hIJHE-U3eD0FmpBrzA__itemrep@2x/img/nnJlWz7nWcNTdvcXnH4OT11LKAk=/fit-in/492x600/filters:strip_icc()/pic6705097.jpg",
    "totalPlays": 0,
    "publishedYear": 2022,
    "subtitle": "아크로폴리스",
    "bggUrl": "https://boardgamegeek.com/boardgame/357563",
    "duration": "20-30",
    "status": "Owned",
  },
  {
    "id": "24068",
    "title": "Shadow Hunters",
    "players": "4-8",
    "playTime": "45",
    "weight": 1.8,
    "imageUrl": "https://cf.geekdo-images.com/_eXzp4yCWA4_b-VmFQf3IA__itemrep@2x/img/6g4a3vFsbFBcdhvCNKL4mSZ-_NU=/fit-in/492x600/filters:strip_icc()/pic1215982.jpg",
    "totalPlays": 0,
    "publishedYear": 2005,
    "subtitle": "섀도우 헌터스",
    "bggUrl": "https://boardgamegeek.com/boardgame/24068",
    "duration": "45",
  },
  {
    "id": "326494",
    "title": "The Adventures of Robin Hood",
    "players": "2-4",
    "playTime": "60",
    "weight": 1.8,
    "imageUrl": "https://cf.geekdo-images.com/QOCGlQyx_HU0nG1oRpeGVg__itemrep@2x/img/GQ6IaIKVkmBhSJWDAwcBjWOEMN4=/fit-in/492x600/filters:strip_icc()/pic6220819.jpg",
    "totalPlays": 0,
    "publishedYear": 2021,
    "subtitle": "로빈 후드의 모험",
    "bggUrl": "https://boardgamegeek.com/boardgame/326494",
    "duration": "60",
  },
  {
    "id": "322785",
    "title": "Suspects: Claire Harper Takes the Stage",
    "players": "1-6",
    "playTime": "60",
    "weight": 1.8,
    "imageUrl": "https://cf.geekdo-images.com/W62RivF2drCQVe6x1L7XiQ__itemrep@2x/img/CIex-tGwKTVtW3f6C3_InJUtU4s=/fit-in/492x600/filters:strip_icc()/pic6039476.png",
    "totalPlays": 0,
    "publishedYear": 2021,
    "subtitle": "용의자들: 클레어 하퍼의 수사일지",
    "bggUrl": "https://boardgamegeek.com/boardgame/322785",
    "duration": "60",
  },
  {
    "id": "258444",
    "title": "Gingerbread House",
    "players": "2-4",
    "playTime": "30-45",
    "weight": 1.8,
    "imageUrl": "https://cf.geekdo-images.com/pRGHRqgkLr6TT6GrXbdoVg__itemrep@2x/img/82Ifrpa7l3S-L-bDM1crszwofuw=/fit-in/492x600/filters:strip_icc()/pic4269457.jpg",
    "totalPlays": 0,
    "publishedYear": 2018,
    "subtitle": "진저브레드 하우스",
    "bggUrl": "https://boardgamegeek.com/boardgame/258444",
    "duration": "30-45",
  },
  {
    "id": "217372",
    "title": "The Quest for El Dorado",
    "players": "2-4",
    "playTime": "30-60",
    "weight": 1.9,
    "imageUrl": "https://cf.geekdo-images.com/b5VyYjNfAxJ4Z-Dx2UWlqg__itemrep@2x/img/WRMjcTjRqs1icMySG0dxNIkLJvc=/fit-in/492x600/filters:strip_icc()/pic7945692.jpg",
    "totalPlays": 0,
    "publishedYear": 2017,
    "subtitle": "황금의 땅 엘도라도",
    "bggUrl": "https://boardgamegeek.com/boardgame/217372",
    "duration": "30-60",
  },
  {
    "id": "115",
    "title": "I'm the Boss!",
    "players": "3-6",
    "playTime": "60",
    "weight": 2,
    "imageUrl": "https://cf.geekdo-images.com/BwLVB048K-u7s_VfRZZibQ__itemrep@2x/img/f__q3R4YBQTzyr_6IpoUcdK0Vdg=/fit-in/492x600/filters:strip_icc()/pic7810845.png",
    "totalPlays": 0,
    "publishedYear": 1994,
    "subtitle": "아임 더 보스!",
    "bggUrl": "https://boardgamegeek.com/boardgame/115",
    "duration": "60",
  },
  {
    "id": "378848",
    "title": "Camel Up: The Card Game",
    "players": "2-6",
    "playTime": "30-45",
    "weight": 2.1,
    "imageUrl": "https://cf.geekdo-images.com/ucbPtg8yzolVPyeSPiXZ5A__itemrep@2x/img/iZSKBklAOAx_C8jMitH6sS9BQo8=/fit-in/492x600/filters:strip_icc()/pic7288330.jpg",
    "totalPlays": 0,
    "publishedYear": 2023,
    "subtitle": "카멜업: 카드 게임",
    "bggUrl": "https://boardgamegeek.com/boardgame/378848",
    "duration": "30-45",
  },
  {
    "id": "244331",
    "title": "Blue Lagoon",
    "players": "2-4",
    "playTime": "30-45",
    "weight": 2,
    "imageUrl": "https://cf.geekdo-images.com/wFggDB9IbU47-drR4GUQBw__itemrep@2x/img/DNQ5d0KhxlnFMaQBuu-qbxhkoU8=/fit-in/492x600/filters:strip_icc()/pic4122624.png",
    "totalPlays": 0,
    "publishedYear": 2018,
    "subtitle": "블루라군",
    "bggUrl": "https://boardgamegeek.com/boardgame/244331",
    "duration": "30-45",
  },
  {
    "id": "478",
    "title": "Citadels",
    "players": "2-8",
    "playTime": "30-60",
    "weight": 2,
    "imageUrl": "https://cf.geekdo-images.com/sHd0jkZZLDgixHjAXtn7kA__itemrep/img/AWV2LUDla1LJMWg0IZC-2gRxI6I=/fit-in/246x300/filters:strip_icc()/pic3119514.jpg",
    "totalPlays": 0,
    "publishedYear": 2000,
    "subtitle": "시타델",
    "bggUrl": "https://boardgamegeek.com/boardgame/478",
    "duration": "30-60",
  },
  {
    "id": "161614",
    "title": "Stockpile",
    "players": "2-5",
    "playTime": "45-60",
    "weight": 2.1,
    "imageUrl": "https://cf.geekdo-images.com/T7CvF_oFrEMNgS0Eyrbr5g__itemrep@2x/img/1b69C9N3rgTglARF3fzCDO4Ydsk=/fit-in/492x600/filters:strip_icc()/pic2537618.jpg",
    "totalPlays": 0,
    "publishedYear": 2015,
    "subtitle": "스탁파일",
    "bggUrl": "https://boardgamegeek.com/boardgame/161614",
    "duration": "45-60",
  },
  {
    "id": "280453",
    "title": "Masters of Renaissance: Lorenzo il Magnifico - The Card Game",
    "players": "1-4",
    "playTime": "30-45",
    "weight": 2.1,
    "imageUrl": "https://cf.geekdo-images.com/-zdSgCFfOGAsgZ6M-Rjw1w__itemrep@2x/img/LmIgg6ws9eiugW1ajSw3rVcf_tA=/fit-in/492x600/filters:strip_icc()/pic4782992.jpg",
    "totalPlays": 0,
    "publishedYear": 2019,
    "subtitle": "르네상스의 거장들: 위대한 로렌초 - 카드게임",
    "bggUrl": "https://boardgamegeek.com/boardgame/280453",
    "duration": "30-45",
  },
  {
    "id": "100901",
    "title": "Flash Point: Fire Rescue",
    "players": "2-6",
    "playTime": "45",
    "weight": 2.2,
    "imageUrl": "https://cf.geekdo-images.com/v6bTbxeprDFj1nN4AenvjA__itemrep@2x/img/rupUkzzDqiJx1wd4yXFS8Dt5Yhs=/fit-in/492x600/filters:strip_icc()/pic1129370.jpg",
    "totalPlays": 0,
    "publishedYear": 2011,
    "subtitle": "플래시 포인트: 화재 구조",
    "bggUrl": "https://boardgamegeek.com/boardgame/100901",
    "duration": "45",
  },
  {
    "id": "356033",
    "title": "Libertalia: Winds of Galecrest",
    "players": "1-6",
    "playTime": "45-60",
    "weight": 2.2,
    "imageUrl": "https://cf.geekdo-images.com/6e-V_Xb2IsAsMNXU18Fi6A__itemrep@2x/img/i-x22ekmJfKuFHtae4NL51fvAMU=/fit-in/492x600/filters:strip_icc()/pic6669033.jpg",
    "totalPlays": 0,
    "publishedYear": 2022,
    "subtitle": "리버탈리아: 게일크레스트의 바람",
    "bggUrl": "https://boardgamegeek.com/boardgame/356033",
    "duration": "45-60",
  },
  {
    "id": "346205",
    "title": "Explorers of the Woodlands",
    "players": "1-4",
    "playTime": "30-45",
    "weight": 2.2,
    "imageUrl": "https://cf.geekdo-images.com/LA0EJtun_-1KZsu0Yznxlg__itemrep@2x/img/rB-7mUsDy4SfhUgg6h7Z2kXAyLc=/fit-in/492x600/filters:strip_icc()/pic6753479.png",
    "totalPlays": 0,
    "subtitle": "우드랜드의 탐험가",
    "bggUrl": "https://boardgamegeek.com/boardgame/346205",
    "duration": "30-45",
    "publishedYear": 2023,
  },
  {
    "id": "424567",
    "title": "Stella Quest",
    "players": "2-4",
    "playTime": "30-45",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/m6Xr5i_VniFbRl6iazdirg__itemrep@2x/img/YZVbtakxUlA52E_e-O0SlrWUJ8o=/fit-in/492x600/filters:strip_icc()/pic8302898.jpg",
    "totalPlays": 0,
    "publishedYear": 2024,
    "subtitle": "별의 소원",
    "bggUrl": "https://boardgamegeek.com/boardgame/424567",
    "duration": "30-45",
  },
  {
    "id": "194607",
    "title": "Mystic Vale",
    "players": "2-4",
    "playTime": "45",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/2cf8lebaIrJ8Z62HGEs2wQ__itemrep/img/fHUOINdWuIy88ikjNIVqg-4_Gcw=/fit-in/246x300/filters:strip_icc()/pic3287905.png",
    "totalPlays": 0,
    "publishedYear": 2016,
    "subtitle": "미스틱 베일",
    "bggUrl": "https://boardgamegeek.com/boardgame/194607",
    "duration": "45",
  },
  {
    "id": "8217",
    "title": "San Juan",
    "players": "2-4",
    "playTime": "45-60",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/kiD03bslLpN_0Qe1LJ8OGg__itemrep/img/sW_yt7M1ZhWWPELnZHyzQ2Wjqs4=/fit-in/246x300/filters:strip_icc()/pic174174.jpg",
    "totalPlays": 0,
    "publishedYear": 2004,
    "subtitle": "산 후앙",
    "bggUrl": "https://boardgamegeek.com/boardgame/8217",
    "duration": "45-60",
  },
  {
    "id": "207010",
    "title": "Paramedics: Clear!",
    "players": "1-4",
    "playTime": "30-45",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/fTR9C-LS8IXH4IGFwnxJ6w__itemrep@2x/img/9-OgbqnKesMM_7Kyt9S7z7ojl6M=/fit-in/492x600/filters:strip_icc()/pic3475402.jpg",
    "totalPlays": 0,
    "publishedYear": 2017,
    "subtitle": "파라메딕스 클리어",
    "bggUrl": "https://boardgamegeek.com/boardgame/207010",
    "duration": "30-45",
  },
  {
    "id": "1159",
    "title": "Evo",
    "players": "3-5",
    "playTime": "60-90",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/OlpxzxL2SVr4gQvCSaL4JQ__itemrep@2x/img/DUV4sHHYO6LtmIPtMcHKGtEv1Rs=/fit-in/492x600/filters:strip_icc()/pic1100790.jpg",
    "totalPlays": 0,
    "publishedYear": 2001,
    "subtitle": "에보",
    "bggUrl": "https://boardgamegeek.com/boardgame/1159",
    "duration": "60-90",
  },
  {
    "id": "9217",
    "title": "Saint Petersburg",
    "players": "2-4",
    "playTime": "45-60",
    "weight": 2.4,
    "imageUrl": "https://cf.geekdo-images.com/Yoidfpvt2eACASYUpbmsyg__itemrep@2x/img/2gr_zhdDku8Gr-PbdCzzSpdOPvc=/fit-in/492x600/filters:strip_icc()/pic246360.jpg",
    "totalPlays": 0,
    "publishedYear": 2004,
    "subtitle": "상트 페테르부르크",
    "bggUrl": "https://boardgamegeek.com/boardgame/9217",
    "duration": "45-60",
  },
  {
    "id": "5",
    "title": "Acquire",
    "players": "2-6",
    "playTime": "90",
    "weight": 2.5,
    "imageUrl": "https://cf.geekdo-images.com/gIQlWhlaqjPiunZjjwz_XA__itemrep@2x/img/E2qJAiswH63IGDeKfkfCCfkSnjg=/fit-in/492x600/filters:strip_icc()/pic8483227.jpg",
    "totalPlays": 0,
    "publishedYear": 1963,
    "subtitle": "어콰이어",
    "bggUrl": "https://boardgamegeek.com/boardgame/5",
    "duration": "90",
  },
  {
    "id": "170042",
    "title": "Raiders of the North Sea",
    "players": "2-4",
    "playTime": "60-80",
    "weight": 2.6,
    "imageUrl": "https://cf.geekdo-images.com/hXdfAhgZ8OeyWLunt36wlw__itemrep@2x/img/adAHWYGJCMszwmxuAYsgTaKhyug=/fit-in/492x600/filters:strip_icc()/pic3578101.jpg",
    "totalPlays": 0,
    "publishedYear": 2015,
    "subtitle": "북해의 침략자",
    "bggUrl": "https://boardgamegeek.com/boardgame/170042",
    "duration": "60-80",
  },
  {
    "id": "481",
    "title": "Carolus Magnus",
    "players": "2-4",
    "playTime": "45-60",
    "weight": 2.6,
    "imageUrl": "https://cf.geekdo-images.com/HT2eLqEbib9ptJQrVSzOfg__itemrep/img/dfGkXJSj7urbuHu2n1D5xLITi9I=/fit-in/246x300/filters:strip_icc()/pic130679.jpg",
    "totalPlays": 0,
    "publishedYear": 2000,
    "subtitle": "카를로스 마그너스",
    "bggUrl": "https://boardgamegeek.com/boardgame/481",
    "duration": "45-60",
  },
  {
    "id": "269207",
    "title": "The Taverns of Tiefenthal",
    "players": "2-4",
    "playTime": "60",
    "weight": 2.7,
    "imageUrl": "https://cf.geekdo-images.com/H-AU-nhjCbaxWlWj_O-eFw__itemrep@2x/img/8LH8v96SQye_kDFtH5j68a0ikhQ=/fit-in/492x600/filters:strip_icc()/pic4873141.jpg",
    "totalPlays": 0,
    "publishedYear": 2019,
    "subtitle": "티펜탈의 선술집",
    "bggUrl": "https://boardgamegeek.com/boardgame/269207",
    "duration": "60",
  },
  {
    "id": "236457",
    "title": "Architects of the West Kingdom",
    "players": "1-5",
    "playTime": "60-80",
    "weight": 2.8,
    "imageUrl": "https://cf.geekdo-images.com/OAX7HfOz-9N60StgADzd0g__itemrep@2x/img/Thdq9gV27yx_bMAueNjD2e4jdw8=/fit-in/492x600/filters:strip_icc()/pic3781944.png",
    "totalPlays": 2,
    "publishedYear": 2018,
    "subtitle": "서쪽 왕국의 건축가",
    "bggUrl": "https://boardgamegeek.com/boardgame/236457",
    "duration": "60-80",
  },
  {
    "id": "368058",
    "title": "The Wolves",
    "players": "2-5",
    "playTime": "60-75",
    "weight": 2.8,
    "imageUrl": "https://cf.geekdo-images.com/6irYLjUf_o0rK7E_4qI-gw__itemrep@2x/img/VDYAHaQAAjgwL_Nrl9KMKVp0FcQ=/fit-in/492x600/filters:strip_icc()/pic6990829.png",
    "totalPlays": 2,
    "publishedYear": 2022,
    "subtitle": "더 울브즈",
    "bggUrl": "https://boardgamegeek.com/boardgame/368058",
    "duration": "60-75",
  },
  {
    "id": "295895",
    "title": "Distilled",
    "players": "1-5",
    "playTime": "30-150",
    "weight": 3,
    "imageUrl": "https://cf.geekdo-images.com/8YPBUoAlAvGSfcRTxr7EZQ__itemrep@2x/img/Z8zCNhXqFN1jGCh3MgKT3qDQa3w=/fit-in/492x600/filters:strip_icc()/pic7104213.png",
    "totalPlays": 0,
    "publishedYear": 2023,
    "subtitle": "디스틸드",
    "bggUrl": "https://boardgamegeek.com/boardgame/295895",
    "duration": "30-150",
  },
  {
    "id": "354132",
    "title": "East India Companies",
    "players": "2-4",
    "playTime": "90-120",
    "weight": 3,
    "imageUrl": "https://cf.geekdo-images.com/j3B__Qgm8PeUD0cl2Sue-w__itemrep@2x/img/76XO2xYPER5euxXrMeJqhNRSoNk=/fit-in/492x600/filters:strip_icc()/pic7064114.jpg",
    "totalPlays": 0,
    "publishedYear": 2023,
    "subtitle": "동인도 회사",
    "bggUrl": "https://boardgamegeek.com/boardgame/354132",
    "duration": "90-120",
  },
  {
    "id": "318983",
    "title": "Faiyum",
    "players": "1-5",
    "playTime": "60-120",
    "weight": 3.1,
    "imageUrl": "https://cf.geekdo-images.com/sl0ReaWGqY1LQjNoGtCPWg__itemrep@2x/img/dTT3A92GuKM6UoJ7tAHuH0nHFMQ=/fit-in/492x600/filters:strip_icc()/pic5638086.jpg",
    "totalPlays": 0,
    "publishedYear": 2020,
    "subtitle": "파이윰",
    "bggUrl": "https://boardgamegeek.com/boardgame/318983",
    "duration": "60-120",
  },
  {
    "id": "231733",
    "title": "Obsession",
    "players": "1-4",
    "playTime": "30-90",
    "weight": 3.1,
    "imageUrl": "https://cf.geekdo-images.com/sy89BiuZXfbSnG7Cag9tBQ__itemrep@2x/img/EZ23fmdBQDkOt9KSWhesxQj0xw0=/fit-in/492x600/filters:strip_icc()/pic5902073.png",
    "totalPlays": 0,
    "publishedYear": 2018,
    "subtitle": "업세션",
    "bggUrl": "https://boardgamegeek.com/boardgame/231733",
    "duration": "30-90",
  },
  {
    "id": "245638",
    "title": "Coimbra",
    "players": "2-4",
    "playTime": "60-90",
    "weight": 3.2,
    "imageUrl": "https://cf.geekdo-images.com/JJFHx0RiUBYdy9bHAgVSuA__itemrep@2x/img/A-nLCpQuCJQqpMce-E2eurkCFUI=/fit-in/492x600/filters:strip_icc()/pic3956079.jpg",
    "totalPlays": 0,
    "publishedYear": 2018,
    "subtitle": "코임브라",
    "bggUrl": "https://boardgamegeek.com/boardgame/245638",
    "duration": "60-90",
  },
  {
    "id": "30380",
    "title": "Cuba",
    "players": "2-5",
    "playTime": "75-120",
    "weight": 3.3,
    "imageUrl": "https://cf.geekdo-images.com/nRp3AZhQD99Ajp5-96km-w__itemrep@2x/img/1Ma43mwSrW4e1KGWVSZWZyJglik=/fit-in/492x600/filters:strip_icc()/pic1205385.jpg",
    "totalPlays": 0,
    "publishedYear": 2007,
    "subtitle": "쿠바",
    "bggUrl": "https://boardgamegeek.com/boardgame/30380",
    "duration": "75-120",
  },
  {
    "id": "283948",
    "title": "Marco Polo II: In the Service of the Khan",
    "players": "2-4",
    "playTime": "60-120",
    "weight": 3.4,
    "imageUrl": "https://cf.geekdo-images.com/rc7CQ5l95ZFoKq3iBVqjgg__itemrep@2x/img/fn3uMoZaY_BgX_5hzZmmBXIhuMw=/fit-in/492x600/filters:strip_icc()/pic5543526.jpg",
    "totalPlays": 6,
    "publishedYear": 2019,
    "subtitle": "마르코 폴로 2: 위대한 칸의 이름으로",
    "bggUrl": "https://boardgamegeek.com/boardgame/283948",
    "duration": "60-120",
    "status": "Owned",
  },
  {
    "id": "332772",
    "title": "Revive",
    "players": "1-4",
    "playTime": "90-120",
    "weight": 3.5,
    "imageUrl": "https://cf.geekdo-images.com/V0OZ9QR0pC9G5t5i9MoZTQ__itemrep@2x/img/sZCwIiabtBEFxuv1qHVCg31A-qA=/fit-in/492x600/filters:strip_icc()/pic6950224.jpg",
    "totalPlays": 0,
    "publishedYear": 2022,
    "subtitle": "리바이브",
    "bggUrl": "https://boardgamegeek.com/boardgame/332772",
    "duration": "90-120",
  },
  {
    "id": "13884",
    "title": "The Scepter of Zavandor",
    "players": "2-6",
    "playTime": "120-180",
    "weight": 3.5,
    "imageUrl": "https://cf.geekdo-images.com/gOx-JhEJb5F9z-Tp9Fx9aA__itemrep@2x/img/Pvf9hZc2aRiWcWHdLuHlDFaoYVw=/fit-in/492x600/filters:strip_icc()/pic8379924.png",
    "totalPlays": 0,
    "publishedYear": 2004,
    "subtitle": "자반도르의 셉터",
    "bggUrl": "https://boardgamegeek.com/boardgame/13884",
    "duration": "120-180",
  },
  {
    "id": "18602",
    "title": "Caylus",
    "players": "2-5",
    "playTime": "60-150",
    "weight": 3.8,
    "imageUrl": "https://cf.geekdo-images.com/yC7nOSc1x5PT-oNnh6TEcQ__itemrep@2x/img/exeGiUiVInCqKXpdBmHA_Os7UuE=/fit-in/492x600/filters:strip_icc()/pic1638795.jpg",
    "totalPlays": 0,
    "publishedYear": 2005,
    "subtitle": "케일러스",
    "bggUrl": "https://boardgamegeek.com/boardgame/18602",
    "duration": "60-150",
  },
  {
    "id": "310873",
    "title": "Carnegie",
    "players": "1-4",
    "playTime": "90-120",
    "weight": 3.8,
    "imageUrl": "https://cf.geekdo-images.com/0qxz9DRRhsJrIW1TJ-kz0w__itemrep@2x/img/nU6bDOpmEPX_VEoJwygI7pETpmQ=/fit-in/492x600/filters:strip_icc()/pic5710736.jpg",
    "totalPlays": 1,
    "publishedYear": 2022,
    "subtitle": "카네기",
    "bggUrl": "https://boardgamegeek.com/boardgame/310873",
    "duration": "90-120",
  },
  {
    "id": "383179",
    "title": "Age of Innovation",
    "players": "1-5",
    "playTime": "40-200",
    "weight": 4.3,
    "imageUrl": "https://cf.geekdo-images.com/D1vrcFEptCEoD8Z6s_iRfw__itemrep@2x/img/hp3aw2I9vgAjr88P3ueeocZSSCI=/fit-in/492x600/filters:strip_icc()/pic7430993.jpg",
    "totalPlays": 3,
    "publishedYear": 2023,
    "subtitle": "혁신의 시대",
    "bggUrl": "https://boardgamegeek.com/boardgame/383179",
    "duration": "40-200",
  },
  {
    "id": "184267",
    "title": "On Mars",
    "players": "1-4",
    "playTime": "90-150",
    "weight": 4.6,
    "imageUrl": "https://cf.geekdo-images.com/Nm0Iw8NoiM9V8IsifimGBw__itemrep@2x/img/aLdX7zkTQlx_mPsMdL0iVBnSVTM=/fit-in/492x600/filters:strip_icc()/pic4357658.jpg",
    "totalPlays": 0,
    "publishedYear": 2020,
    "subtitle": "온 마스",
    "bggUrl": "https://boardgamegeek.com/boardgame/184267",
    "duration": "90-150",
  },
  {
    "id": "130751",
    "title": "Spooky Spells",
    "players": "3-10",
    "playTime": "15-30",
    "weight": 1,
    "imageUrl": "https://cf.geekdo-images.com/5tL1nEQ-M0fx1ZnNxEM0mw__itemrep/img/j33FzBRa_omNLhpk4a5WGr0vIMc=/fit-in/246x300/filters:strip_icc()/pic1420520.jpg",
    "totalPlays": 0,
    "publishedYear": 2012,
    "subtitle": "스푸키 스펠",
    "bggUrl": "https://boardgamegeek.com/boardgame/130751",
    "duration": "15-30",
  },
  {
    "id": "3337",
    "title": "Lobo 77",
    "players": "2-8",
    "playTime": "15",
    "weight": 1.1,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqRiokWAcbzcLrrGkL8OF6FD6KFhprX_51zA&s",
    "totalPlays": 0,
    "publishedYear": 1993,
    "subtitle": "로보 77",
    "bggUrl": "https://boardgamegeek.com/boardgame/3337",
    "duration": "15",
  },
  {
    "id": "163166",
    "title": "One Night Ultimate Werewolf: Daybreak",
    "players": "3-10",
    "playTime": "10",
    "weight": 1.4,
    "imageUrl": "https://cf.geekdo-images.com/-jMVcPlkpLcs-2nA_htb8g__itemrep/img/T3NfYAAbfC8uUjwp9PGniGaW0dI=/fit-in/246x300/filters:strip_icc()/pic2225958.jpg",
    "totalPlays": 0,
    "publishedYear": 2015,
    "subtitle": "한밤의 늑대인간: 황혼에서 새벽까지",
    "bggUrl": "https://boardgamegeek.com/boardgame/163166",
    "duration": "10",
  },
  {
    "id": "139030",
    "title": "Mascarade",
    "players": "2-13",
    "playTime": "30",
    "weight": 1.5,
    "imageUrl": "https://cf.geekdo-images.com/OS3ckk3rZbwFi8en1rjiGQ__itemrep@2x/img/WZ37aJm-R5zFH-_LbDKINxS6SWQ=/fit-in/492x600/filters:strip_icc()/pic1762410.jpg",
    "totalPlays": 0,
    "publishedYear": 2013,
    "subtitle": "마스카라드",
    "bggUrl": "https://boardgamegeek.com/boardgame/139030",
    "duration": "30",
  },
  {
    "id": "41114",
    "title": "The Resistance",
    "players": "5-10",
    "playTime": "30",
    "weight": 1.6,
    "imageUrl": "https://cf.geekdo-images.com/cAPTkL2BR3snLO71dkH8rw__itemrep@2x/img/5qEOS48H-iQzqqK5NUv4Up90gvs=/fit-in/492x600/filters:strip_icc()/pic2576459.jpg",
    "totalPlays": 0,
    "publishedYear": 2009,
    "subtitle": "레지스탕스",
    "bggUrl": "https://boardgamegeek.com/boardgame/41114",
    "duration": "30",
  },
  {
    "id": "340364",
    "title": "Minivilles 2",
    "players": "2-5",
    "playTime": "30-45",
    "weight": 1.6,
    "imageUrl": "https://cf.geekdo-images.com/NFIzv8Yr3_u7nc_PBoYntQ__itemrep@2x/img/PWWoMfO-7nMhgNHV2Ne7ybMCFLU=/fit-in/492x600/filters:strip_icc()/pic6221820.png",
    "totalPlays": 0,
    "publishedYear": 2021,
    "subtitle": "미니빌 2",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/340364",
    "duration": "30-45",
  },
  {
    "id": "318977",
    "title": "MicroMacro: Crime City",
    "players": "1-4",
    "playTime": "15-45",
    "weight": 1.1,
    "imageUrl": "https://cf.geekdo-images.com/bLL3P-G25nIUkFjHxfJfnw__itemrep/img/CHbB8dFjnR8N3Mzuq0OQpSCLfJ4=/fit-in/246x300/filters:strip_icc()/pic7632081.jpg",
    "totalPlays": 0,
    "publishedYear": 2020,
    "subtitle": "미크로 마크로: 크라임 시티",
    "bggUrl": "https://boardgamegeek.com/boardgame/318977",
    "duration": "15-45",
  },
  {
    "id": "338834",
    "title": "MicroMacro: Crime City - Full House",
    "players": "1-4",
    "playTime": "15-45",
    "weight": 1.2,
    "imageUrl": "https://cf.geekdo-images.com/bNuZIssobDbFYaLbgMofgw__itemrep/img/lV9teFwDwT0Qcep3TKOp4Ojc4dQ=/fit-in/246x300/filters:strip_icc()/pic6242068.jpg",
    "totalPlays": 0,
    "publishedYear": 2021,
    "subtitle": "미크로 마크로: 크라임 시티- 풀하우스",
    "bggUrl": "https://boardgamegeek.com/boardgame/338834",
    "duration": "15-45",
  },
  {
    "id": "364766",
    "title": "MicroMacro: Crime City - All In",
    "players": "1-4",
    "playTime": "15-45",
    "weight": 1.1,
    "imageUrl": "https://cf.geekdo-images.com/sAYWQ4BFiLTF137eYGwRhQ__itemrep@2x/img/jhq2CzQapHqDHhJP8PR2PQXZ-Os=/fit-in/492x600/filters:strip_icc()/pic8987379.png",
    "totalPlays": 0,
    "publishedYear": 2022,
    "subtitle": "미크로 마크로: 크라임시티- 올인",
    "bggUrl": "https://boardgamegeek.com/boardgame/364766",
    "duration": "15-45",
  },
  {
    "id": "371942",
    "title": "The White Castle",
    "players": "1-4",
    "playTime": "80",
    "weight": 3.1,
    "imageUrl": "https://cf.geekdo-images.com/qXT1U-nFh9PE8ujfdmI7dA__itemrep@2x/img/l5v97elMDRiO-94ghjwGLjal9zQ=/fit-in/492x600/filters:strip_icc()/pic7754663.jpg",
    "totalPlays": 0,
    "publishedYear": 2023,
    "subtitle": "백로성",
    "bggUrl": "https://boardgamegeek.com/boardgame/371942",
    "duration": "80",
  },
  {
    "id": "385761",
    "title": "Faraway",
    "players": "2-6",
    "playTime": "15-25",
    "weight": 1.9,
    "imageUrl": "https://cf.geekdo-images.com/u1cwi9BWSKsPxSkVO0BzbA__itemrep@2x/img/VV2_TwOzKj4Cy0v_y7TH6PwzDPs=/fit-in/492x600/filters:strip_icc()/pic7570101.png",
    "totalPlays": 0,
    "publishedYear": 2023,
    "subtitle": "파러웨이",
    "bggUrl": "https://boardgamegeek.com/boardgame/385761",
    "duration": "15-25",
  },
  {
    "id": "37628",
    "title": "Haggis",
    "players": "2-4",
    "playTime": "45",
    "weight": 2.1,
    "imageUrl": "https://cf.geekdo-images.com/IrYxdDL_emPurvpg_lRSgA__itemrep@2x/img/0L7lhBrLfTXLxnUjuTmZJe3Iu_4=/fit-in/492x600/filters:strip_icc()/pic7669050.jpg",
    "totalPlays": 0,
    "publishedYear": 2010,
    "subtitle": "해기스",
    "bggUrl": "https://boardgamegeek.com/boardgame/37628",
    "duration": "45",
  },
  {
    "id": "424784",
    "title": "Arkham Horror: Lovecraft Letter",
    "players": "2-6",
    "playTime": "20",
    "weight": 1.4,
    "imageUrl": "https://cf.geekdo-images.com/hLfQAtkN8m06_L3xAtqXEQ__itemrep@2x/img/DZn_Jmkmo9gNI0lwAYytSb9DtSc=/fit-in/492x600/filters:strip_icc()/pic8544768.png",
    "totalPlays": 0,
    "publishedYear": 2025,
    "subtitle": "러브크래프트 레터: 아컴호러",
    "bggUrl": "https://boardgamegeek.com/boardgame/424784",
    "duration": "20",
  },
  {
    "id": "368837",
    "title": "Quickshot",
    "players": "1-7",
    "playTime": "10-15",
    "weight": 1,
    "imageUrl": "https://cf.geekdo-images.com/UuVaopAYiK2kh17AcjJCYg__itemrep@2x/img/gq0aHzRrmuTmdMjZ-5Jk-9MHNPY=/fit-in/492x600/filters:strip_icc()/pic7518243.png",
    "totalPlays": 0,
    "publishedYear": 2022,
    "subtitle": "퀵샷 서바이벌",
    "bggUrl": "https://boardgamegeek.com/boardgame/368837",
    "duration": "10-15",
  },
  {
    "id": "217020",
    "title": "Truck Off: The Food Truck Frenzy",
    "players": "2-6",
    "playTime": "30",
    "weight": 1.4,
    "imageUrl": "https://cf.geekdo-images.com/aIWQuhObBhD1mL9jb3ljkQ__itemrep@2x/img/fon0kJ5m7IEcn-DqvjV7gevn6Ls=/fit-in/492x600/filters:strip_icc()/pic3383124.jpg",
    "totalPlays": 0,
    "publishedYear": 2017,
    "subtitle": "광란의 푸드트럭: 이것은 요식업이 아닌 전쟁",
    "bggUrl": "https://boardgamegeek.com/boardgame/217020",
    "duration": "30",
  },
  {
    "id": "215",
    "title": "Tichu",
    "players": "3-10",
    "playTime": "60",
    "weight": 2.3,
    "imageUrl": "https://cf.geekdo-images.com/gz8_8iYP2SSGVAxpp7CwLg__itemrep@2x/img/CEs0iDgpr59ArupeFpyZ_VXuBSQ=/fit-in/492x600/filters:strip_icc()/pic5854968.png",
    "totalPlays": 1,
    "publishedYear": 1991,
    "subtitle": "티츄",
    "bggUrl": "https://boardgamegeek.com/boardgame/215",
    "duration": "60",
  },
  {
    "id": "427278",
    "title": "Roaring 20s",
    "players": "3-5",
    "playTime": "15-20",
    "weight": 1.3,
    "imageUrl": "https://cf.geekdo-images.com/zCvWgidv-VPhYiJY1qcQ_g__itemrep@2x/img/MHHFrrJ2T1M1IrqAOKcdjBdYzWw=/fit-in/492x600/filters:strip_icc()/pic8394529.jpg",
    "totalPlays": 0,
    "publishedYear": 2024,
    "subtitle": "파티사우루스 20s",
    "bggUrl": "https://boardgamegeek.com/boardgame/427278",
    "duration": "15-20",
  },
  {
    "id": "419195",
    "title": "Fishing",
    "players": "3-5",
    "playTime": "20",
    "weight": 1.9,
    "imageUrl": "https://cf.geekdo-images.com/LjqYcVKq6YrQ0rJ4H4Lusg__itemrep@2x/img/hDBMZSUaYrHdyMLR7J7kWEpq6_A=/fit-in/492x600/filters:strip_icc()/pic8149442.png",
    "totalPlays": 0,
    "publishedYear": 2024,
    "subtitle": "피쉬 앤 트릭",
    "bggUrl": "https://boardgamegeek.com/boardgame/419195",
    "duration": "20",
  },
  {
    "id": "12942",
    "title": "No Thanks!",
    "players": "3-7",
    "playTime": "20",
    "weight": 1.1,
    "imageUrl": "https://cf.geekdo-images.com/2P4-gR4xYLnfZtljfc2dRA__itemrep@2x/img/1_iqELggbPDA-RylA8FQu6aLq1g=/fit-in/492x600/filters:strip_icc()/pic2602161.jpg",
    "totalPlays": 0,
    "publishedYear": 2004,
    "subtitle": "노 땡스!",
    "bggUrl": "https://boardgamegeek.com/boardgame/12942",
    "duration": "20",
  },
  {
    "id": "172998",
    "title": "Mighty",
    "players": "3-8",
    "playTime": "30-60",
    "weight": 2.8,
    "imageUrl": "https://cf.geekdo-images.com/fbFfXFaa1qHpf8gh1WUCCA__itemrep@2x/img/4L6zloetxW_QIMfM_vdCAPZQjoQ=/fit-in/492x600/filters:strip_icc()/pic7672998.jpg",
    "totalPlays": 0,
    "publishedYear": 1975,
    "subtitle": "마이티",
    "bggUrl": "https://boardgamegeek.com/boardgame/172998",
    "duration": "30-60",
  },
  {
    "id": "437879",
    "title": "Cup the Crab",
    "players": "3-5",
    "playTime": "15",
    "weight": 1.3,
    "imageUrl": "https://cf.geekdo-images.com/OOijayUyi0I2LEdYouwtSA__itemrep@2x/img/RJWjTgoZDy7Lg7ZBiaH3cLXN_MA=/fit-in/492x600/filters:strip_icc()/pic8808467.png",
    "totalPlays": 0,
    "publishedYear": 2025,
    "subtitle": "컵 더 크랩",
    "bggUrl": "https://boardgamegeek.com/boardgame/437879",
    "duration": "15",
  },
  {
    "id": "206",
    "title": "Jalape-NO!",
    "players": "3-9",
    "playTime": "15",
    "weight": 1.4,
    "imageUrl": "https://cf.geekdo-images.com/m8UmH-2gCwiv3cI2jsxFyg__itemrep@2x/img/vPAWMiBu9s1bhwTOSYuHWALVSro=/fit-in/492x600/filters:strip_icc()/pic7976010.png",
    "totalPlays": 0,
    "publishedYear": 1998,
    "subtitle": "할라피-노!",
    "bggUrl": "https://boardgamegeek.com/boardgame/206",
    "duration": "15",
  },
  {
    "id": "387388",
    "title": "Nanatoridori",
    "players": "2-6",
    "playTime": "10-15",
    "weight": 1.2,
    "imageUrl": "https://cf.geekdo-images.com/NBgCJ5Xam4XJQIxrD_IadA__itemrep@2x/img/a9mZb-V63T5LO0MW3gNRWElpJHo=/fit-in/492x600/filters:strip_icc()/pic8267729.jpg",
    "totalPlays": 0,
    "publishedYear": 2023,
    "subtitle": "가지각새",
    "bggUrl": "https://boardgamegeek.com/boardgame/387388",
    "duration": "10-15",
  },
  {
    "id": "297129",
    "title": "Jekyll vs Hyde",
    "players": "2",
    "playTime": "20",
    "weight": 1.9,
    "imageUrl": "https://cf.geekdo-images.com/b7ElE00K6FojMB77rDy7cg__itemrep@2x/img/ATL0k1bQ8GFoXrwQnyLbOIJCbu8=/fit-in/492x600/filters:strip_icc()/pic5316646.jpg",
    "totalPlays": 1,
    "publishedYear": 2021,
    "subtitle": "지킬 vs 하이드",
    "bggUrl": "https://boardgamegeek.com/boardgame/297129",
    "duration": "20",
  },
  {
    "id": "406854",
    "title": "Odin",
    "players": "2-6",
    "playTime": "15",
    "weight": 1.2,
    "imageUrl": "https://cf.geekdo-images.com/hh5YOk9OQ3e0uJbMOfvT2g__itemrep@2x/img/2LLu8boasR3sir5Q02xLJZi31i8=/fit-in/492x600/filters:strip_icc()/pic7921978.jpg",
    "totalPlays": 0,
    "publishedYear": 2024,
    "subtitle": "오딘",
    "bggUrl": "https://boardgamegeek.com/boardgame/406854",
    "duration": "15",
  },
  {
    "id": "32341",
    "title": "Cockroach Salad",
    "players": "2-6",
    "playTime": "10-20",
    "weight": 1.1,
    "imageUrl": "https://cf.geekdo-images.com/RTPjvs-e_CR8twqHhHyqYw__itemrep/img/7oQF3zDRSgUlyOBR2rV_RrdGg3c=/fit-in/246x300/filters:strip_icc()/pic2303528.jpg",
    "totalPlays": 0,
    "publishedYear": 2007,
    "subtitle": "바퀴벌레 샐러드",
    "bggUrl": "https://boardgamegeek.com/boardgame/32341",
    "duration": "10-20",
  },
  {
    "id": "411567",
    "title": "The Gang",
    "players": "3-6",
    "playTime": "20",
    "weight": 1.6,
    "imageUrl": "https://cf.geekdo-images.com/ydwU0FMlRVa6wt8tOu1tgg__itemrep@2x/img/5AcktNDYWfEXow8X0W15hMi8D7o=/fit-in/492x600/filters:strip_icc()/pic7962719.jpg",
    "totalPlays": 0,
    "publishedYear": 2024,
    "subtitle": "갱스터",
    "bggUrl": "https://boardgamegeek.com/boardgame/411567",
    "duration": "20",
  },
  {
    "id": "381249",
    "title": "Rebel Princess",
    "players": "3-6",
    "playTime": "30",
    "weight": 1.9,
    "imageUrl": "https://cf.geekdo-images.com/HuWvVU2tcff-vu3EjPtk6Q__itemrep@2x/img/SJtG5cYgoTpPTqDv7ggkL19r9Y0=/fit-in/492x600/filters:strip_icc()/pic7605211.jpg",
    "totalPlays": 0,
    "publishedYear": 2023,
    "subtitle": "프린세스의 반란",
    "bggUrl": "https://boardgamegeek.com/boardgame/381249",
    "duration": "30",
  },
  {
    "id": "416851",
    "title": "Castle Combo",
    "players": "2-5",
    "playTime": "25",
    "weight": 1.7,
    "imageUrl": "https://cf.geekdo-images.com/rGomBfj0FGrZM-w3h5HFWQ__itemrep@2x/img/jjp97z9cm3bbV1oaBcl65QJ8pTw=/fit-in/492x600/filters:strip_icc()/pic8250341.png",
    "totalPlays": 2,
    "publishedYear": 2024,
    "subtitle": "캐슬콤보",
    "bggUrl": "https://boardgamegeek.com/boardgame/416851",
    "duration": "25",
  },
  {
    "id": "410338",
    "title": "Rikka",
    "players": "2-5",
    "playTime": "15",
    "weight": 1.3,
    "imageUrl": "https://cf.geekdo-images.com/0EaRm9Oa2waIv-1ObwS6gQ__itemrep@2x/img/ewFUfnTaUWTuHPX3_7PTQFdIuGs=/fit-in/492x600/filters:strip_icc()/pic7977509.jpg",
    "totalPlays": 0,
    "publishedYear": 2023,
    "subtitle": "여섯불꽃",
    "bggUrl": "https://boardgamegeek.com/boardgame/410338",
    "duration": "15",
  },
  {
    "id": "1234",
    "title": "Once Upon a Time: The Storytelling Card Game",
    "players": "2-6",
    "playTime": "30",
    "weight": 1.4,
    "imageUrl": "https://cf.geekdo-images.com/IHYBF2QWcZwlYfH4doj06Q__itemrep/img/gGuMcBjqTxmxGa9OI3T9U_69tWU=/fit-in/246x300/filters:strip_icc()/pic1494028.jpg",
    "totalPlays": 0,
    "publishedYear": 1993,
    "subtitle": "옛날 옛적에",
    "bggUrl": "https://boardgamegeek.com/boardgame/1234",
    "duration": "30",
  },
  {
    "id": "418059",
    "title": "SETI: Search for Extraterrestrial Intelligence",
    "players": "1-4",
    "playTime": "40-160",
    "weight": 3.8,
    "imageUrl": "https://cf.geekdo-images.com/_BUXOVRDU9g_eRwgpR5ZZw__itemrep@2x/img/Sw7_9vvOYAmzW82BfawVy3q2Xro=/fit-in/492x600/filters:strip_icc()/pic8160466.jpg",
    "totalPlays": 1,
    "publishedYear": 2024,
    "subtitle": "세티: 외계의 지성체를 찾아서",
    "bggUrl": "https://boardgamegeek.com/boardgame/418059",
    "duration": "40-160",
  },
  {
    "id": "390092",
    "title": "Ticket to Ride Legacy: Legends of the West",
    "players": "2-5",
    "playTime": "20-60",
    "weight": 2.6,
    "imageUrl": "https://cf.geekdo-images.com/2H0pJddVJA3r6btqRNLG1g__itemrep@2x/img/KMSgaJg2IApbq_JpCqRhRWba5rM=/fit-in/492x600/filters:strip_icc()/pic7541330.png",
    "totalPlays": 0,
    "publishedYear": 2023,
    "subtitle": "티켓 투 라이드 레거시: 서부개척",
    "bggUrl": "https://boardgamegeek.com/boardgame/390092",
    "duration": "20-60",
  },
  {
    "id": "420087",
    "title": "Flip 7",
    "players": "3-18",
    "playTime": "20",
    "weight": 1,
    "imageUrl": "https://cf.geekdo-images.com/YrQxEB9Ef0kQorRApzG5vQ__itemrep@2x/img/L_9BNzwp1B3BMbwbFhO5OGCAm5Y=/fit-in/492x600/filters:strip_icc()/pic8780246.jpg",
    "totalPlays": 1,
    "publishedYear": 2024,
    "subtitle": "플립 7",
    "bggUrl": "https://boardgamegeek.com/boardgame/420087",
    "duration": "20",
  },
  {
    "id": "21348",
    "title": "Ticket to Ride: Marklin",
    "players": "2-5",
    "playTime": "60-80",
    "weight": 2.2,
    "imageUrl": "https://cf.geekdo-images.com/hmjtcaumdyjW_Ncj1duAdw__itemrep@2x/img/T1XAN6353d2kppuWNGANbMuRX20=/fit-in/492x600/filters:strip_icc()/pic162026.jpg",
    "totalPlays": 0,
    "publishedYear": 2006,
    "subtitle": "티켓 투 라이드: 마르클린",
    "bggUrl": "https://boardgamegeek.com/boardgame/21348",
    "duration": "60-80",
  },
  {
    "id": "31627",
    "title": "Ticket to Ride: Nordic Countries",
    "players": "2-3",
    "playTime": "30-60",
    "weight": 2,
    "imageUrl": "https://cf.geekdo-images.com/bCdjNIu-O_SzVCfMLZY_KQ__itemrep/img/5FgSTt_OnWPqzqTd06x8NnVGofg=/fit-in/246x300/filters:strip_icc()/pic7634498.png",
    "totalPlays": 0,
    "publishedYear": 2007,
    "subtitle": "티켓 투 라이드: 노르딕",
    "bggUrl": "https://boardgamegeek.com/boardgame/31627",
    "duration": "30-60",
  },
  {
    "id": "253284",
    "title": "Ticket to Ride: New York",
    "players": "2-4",
    "playTime": "10-15",
    "weight": 1.3,
    "imageUrl": "https://cf.geekdo-images.com/v0YHI6x4g8dJdtSqaxMdiA__itemrep@2x/img/2AsXJcsN5_MfoT1yKKiSS4T9rQc=/fit-in/492x600/filters:strip_icc()/pic4132194.jpg",
    "totalPlays": 0,
    "publishedYear": 2018,
    "subtitle": "티켓 투 라이드: 뉴욕",
    "bggUrl": "https://boardgamegeek.com/boardgame/253284",
    "duration": "10-15",
  },
  {
    "id": "359438",
    "title": "Skymines",
    "players": "1-4",
    "playTime": "75-150",
    "weight": 3.9,
    "imageUrl": "https://cf.geekdo-images.com/loa-OQHFaTlKV2eU_WKVFw__itemrep@2x/img/b1qsIjcUGo5sh8eoA1YS1mNiKG4=/fit-in/492x600/filters:strip_icc()/pic6800089.jpg",
    "totalPlays": 0,
    "publishedYear": 2022,
    "subtitle": "스카이마인",
    "bggUrl": "https://boardgamegeek.com/boardgame/359438",
    "duration": "75-150",
  },
  {
    "id": "253664",
    "title": "Taco  Cat Goat Cheese Pizza",
    "players": "2-8",
    "playTime": "10-15",
    "weight": 1,
    "imageUrl": "uploads/1773453155432-1725012689265250.jpg",
    "publishedYear": 2018,
    "totalPlays": 4,
    "subtitle": "타코 헬로키티 포차코 시나모롤 마이멜로디",
    "status": "Owned",
    "bggUrl": "https://boardgamegeek.com/boardgame/253664",
    "duration": "10-15",
  },
  {
    "id": "446497",
    "title": "Hot Streak",
    "players": "2-8",
    "playTime": "15-30",
    "weight": 1.2,
    "imageUrl": "/uploads/1773453544884-1768969107_327281_fit_850x850.png",
    "publishedYear": 2025,
    "totalPlays": 0,
    "subtitle": "핫스트릭",
    "status": "Owned by Friends",
    "bggUrl": "https://boardgamegeek.com/boardgame/446497",
    "duration": "15-30",
  },
  {
    "id": "408180",
    "title": "Shackleton Base: A Journey to the Moon",
    "players": "1-4",
    "playTime": "60-120",
    "weight": 3.9,
    "imageUrl": "https://cf.geekdo-images.com/XE4S_nXyHVvld2BOrDmA7Q__itemrep@2x/img/GWwU_mVJ3UnT4P2sr1C9L1zJc2Y=/fit-in/492x600/filters:strip_icc()/pic7897060.jpg",
    "subtitle": "섀클턴 베이스",
    "publishedYear": 2024,
    "status": "Preorder",
    "totalPlays": 0,
    "bggUrl": "https://boardgamegeek.com/boardgame/408180",
    "duration": "60-120",
  },
  {
    "id": "326054",
    "title": "冷たい彼女が目覚める前に (Embalming Girl)",
    "players": "3-6",
    "playTime": "15-30",
    "weight": 1.6,
    "imageUrl": "https://cf.geekdo-images.com/AJNJNuzdBjPOMs1GaDxVqw__imagepage/img/jcKsfaIVJRuXHo34SAUVY9lNZJU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic9477510.png",
    "subtitle": "차가운 그녀가 눈을 뜨기 전에",
    "publishedYear": 2020,
    "status": "Owned",
    "totalPlays": 7,
    "bggUrl": "https://boardgamegeek.com/boardgame/326054",
    "duration": "15-30",
  },
  {
    "id": "526",
    "title": "Abalone",
    "players": "2",
    "playTime": "30",
    "weight": 2.1,
    "imageUrl": "https://cf.geekdo-images.com/UzH1jAlqYUH9VEq2Wtvzjw__itemrep@2x/img/XhaqUsE0lD1gBIU9zu4iPfVEJdw=/fit-in/492x600/filters:strip_icc()/pic5253079.jpg",
    "subtitle": "아발론",
    "publishedYear": 1987,
    "status": "Owned",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/526",
    "duration": "30",
  },
  {
    "id": "216132",
    "title": " Clans of Caledonia",
    "players": "1-4",
    "playTime": "30-120",
    "weight": 3.5,
    "imageUrl": "https://cf.geekdo-images.com/SPuwc6RJ6y4PnTH36Pegsg__imagepage@2x/img/r5wyWByPawrxbmHvQKRjGYs76Xw=/fit-in/1800x1200/filters:strip_icc()/pic3511783.png",
    "subtitle": "클랜 오브 칼레도니아",
    "publishedYear": 2017,
    "status": "Preorder",
    "totalPlays": 0,
    "bggUrl": "https://boardgamegeek.com/boardgame/216132",
    "duration": "30-120",
  },
  {
    "id": "70149",
    "title": "Ora et Labora",
    "players": "1-4",
    "playTime": "60-180",
    "weight": 3.9,
    "imageUrl": "https://cf.geekdo-images.com/MLvyN4VJ3QNXBKxli8XLiA__itemrep/img/vaso0GQRh1Agzc9UdMom4KJqKhE=/fit-in/246x300/filters:strip_icc()/pic5089618.jpg",
    "subtitle": "기도하고 일하라",
    "publishedYear": 2011,
    "status": "Owned",
    "totalPlays": 0,
    "bggUrl": "https://boardgamegeek.com/boardgame/70149",
    "duration": "60-180",
  },
  {
    "id": "429405",
    "title": "Orloj: The Prague Astronomical Clock",
    "players": "1-4",
    "playTime": "30-60",
    "weight": 3.6,
    "imageUrl": "https://cf.geekdo-images.com/PhwbD--vP0xEdMD-WZlZTA__itemrep/img/ZP86NmmtlYnLMDQl4mZ1ZbI4lFU=/fit-in/246x300/filters:strip_icc()/pic8685899.png",
    "subtitle": "오를로이: 프라하 천문시계",
    "publishedYear": 2025,
    "status": "Owned",
    "totalPlays": 2,
    "bggUrl": "https://boardgamegeek.com/boardgame/429405",
    "duration": "30-60",
  },
  {
    "id": "339958",
    "title": "Gutenberg",
    "players": "1-4",
    "playTime": "60-120",
    "weight": 2.7,
    "imageUrl": "https://cf.geekdo-images.com/bDUgQ1CfnrTniZytZ5UlQA__itemrep/img/r2kyVH5XVwCeWZr9n6rVMBPx75s=/fit-in/246x300/filters:strip_icc()/pic6618432.jpg",
    "subtitle": "구텐베르크: 활자의 혁명",
    "publishedYear": 2021,
    "status": "Owned",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/339958",
    "duration": "60-120",
  },
  {
    "id": "265736",
    "title": "Tiny Towns",
    "players": "1-6",
    "playTime": "45-60",
    "weight": 2.1,
    "imageUrl": "https://cf.geekdo-images.com/aE1EoOzr530gQin8bj8QDA__itemrep@2x/img/3mUXQjTkzPaYTYFpI5yjUZbc7V0=/fit-in/492x600/filters:strip_icc()/pic4460401.jpg",
    "subtitle": "타이니 타운",
    "publishedYear": 2019,
    "status": "Owned",
    "totalPlays": 2,
    "bggUrl": "https://boardgamegeek.com/boardgame/265736",
    "duration": "45-60",
  },
  {
    "id": "286735",
    "title": "Muffin Time",
    "players": "2-8",
    "playTime": "20-40",
    "weight": 1,
    "imageUrl": "https://cf.geekdo-images.com/WOm-EjxK4o5XVs2t2SrSbA__itemrep/img/pii9pxN-xfBvrq6KUsviVsPv51E=/fit-in/246x300/filters:strip_icc()/pic4949207.png",
    "subtitle": "머핀 타임",
    "publishedYear": 2021,
    "status": "Owned",
    "totalPlays": 5,
    "bggUrl": "https://boardgamegeek.com/boardgame/286735",
    "duration": "20-40",
  },
  {
    "id": "428787",
    "title": "Presages",
    "players": "4-6",
    "playTime": "20-30",
    "weight": 1.8,
    "imageUrl": "https://cf.geekdo-images.com/WngBXWndu_CCMCH9dU64Qg__itemrep@2x/img/A8UVt4zzAHjwdgMLqDhRmGD1jF4=/fit-in/492x600/filters:strip_icc()/pic8642520.jpg",
    "subtitle": "프리세이지",
    "publishedYear": 2025,
    "status": "Owned",
    "totalPlays": 2,
    "bggUrl": "https://boardgamegeek.com/boardgame/428787",
    "duration": "20-30",
  },
  {
    "id": "260704",
    "title": "TonTon",
    "players": "3-5",
    "playTime": "20",
    "weight": 1.8,
    "imageUrl": "https://cf.geekdo-images.com/ChHG1ea6gmXdtSqZICwfag__itemrep@2x/img/RgdlwrEz-4Ln5ieYf4gC1Fngvf4=/fit-in/492x600/filters:strip_icc()/pic4307446.png",
    "subtitle": "통통",
    "publishedYear": 2018,
    "status": "Owned",
    "totalPlays": 0,
    "bggUrl": "https://boardgamegeek.com/boardgame/260704",
    "duration": "20",
  },
  {
    "id": "421630",
    "title": "Moose Match Mayhem",
    "players": "3-6",
    "playTime": "15-20",
    "weight": 1,
    "imageUrl": "https://cf.geekdo-images.com/cczD48bssFw6Ph8HcMhFHg__itemrep@2x/img/G3Qf-wQOyLS45GTt-7ZmIyYaPRs=/fit-in/492x600/filters:strip_icc()/pic8223321.png",
    "subtitle": "무스 무리 모여라!",
    "publishedYear": 2024,
    "status": "Owned",
    "totalPlays": 0,
    "bggUrl": "https://boardgamegeek.com/boardgame/421630",
    "duration": "15-20",
  },
  {
    "id": "431284",
    "title": "Fifty Fruity",
    "players": "2-6",
    "playTime": "15",
    "weight": 2,
    "imageUrl": "https://cf.geekdo-images.com/xA_1GtRi_ITuRkXgZOTzrg__itemrep@2x/img/xtB4bSoVlr1DKpK4plCGP1ZN_1g=/fit-in/492x600/filters:strip_icc()/pic8903961.png",
    "subtitle": "피프티 프루티",
    "publishedYear": 2025,
    "status": "Owned",
    "totalPlays": 0,
    "bggUrl": "https://boardgamegeek.com/boardgame/431284",
    "duration": "15",
  },
  {
    "id": "371330",
    "title": "Luthier: the art of the instrument",
    "players": "1-4",
    "playTime": "60-150",
    "weight": 3.8,
    "imageUrl": "https://cf.geekdo-images.com/NNOCMpxKchQb_ByLmvDfRQ__itemrep@2x/img/M2J4tdnr99xVfOF538q3SDFYFLw=/fit-in/492x600/filters:strip_icc()/pic8145392.png",
    "subtitle": "루티어",
    "publishedYear": 2025,
    "status": "Owned",
    "totalPlays": 0,
    "bggUrl": "https://boardgamegeek.com/boardgame/371330",
    "duration": "60-150",
  },
  {
    "id": "161936",
    "title": "Pandemic Legacy: Season 1",
    "players": "2-4",
    "playTime": "60",
    "weight": 2.8,
    "imageUrl": "https://cf.geekdo-images.com/-Qer2BBPG7qGGDu6KcVDIw__itemrep@2x/img/MjhzWks7Vu-ZhEOtwQYrzSfmoYk=/fit-in/492x600/filters:strip_icc()/pic2452831.png",
    "subtitle": "팬데믹 레거시: 시즌1",
    "publishedYear": 2015,
    "status": "Owned",
    "totalPlays": 0,
    "bggUrl": "https://boardgamegeek.com/boardgame/161936",
    "duration": "60",
  },
  {
    "id": "446519",
    "title": "Miams",
    "players": "1-5",
    "playTime": "15",
    "weight": 1.5,
    "imageUrl": "https://cf.geekdo-images.com/udNqqRInQRK0lfFaaqVw8w__itemrep@2x/img/ipCGZ0Nm1K26L-r8G7ceR80JRJs=/fit-in/492x600/filters:strip_icc()/pic8902039.jpg",
    "subtitle": "냠냠냠",
    "publishedYear": 2025,
    "status": "Owned",
    "totalPlays": 4,
    "bggUrl": "https://boardgamegeek.com/boardgame/446519",
    "duration": "15",
  },
  {
    "id": "428029",
    "title": "Doodle Puzzle",
    "players": "4-8",
    "playTime": "15",
    "weight": 1,
    "imageUrl": "/uploads/1782647095418-99654245585514969_1889782494.png",
    "subtitle": "두들 퍼즐",
    "publishedYear": 2024,
    "status": "Owned",
    "totalPlays": 0,
    "bggUrl": "https://boardgamegeek.com/boardgame/428029",
    "duration": "15",
  },
  {
    "id": "462896",
    "title": "Big or Bang",
    "players": "2-7",
    "playTime": "15-20",
    "weight": 1,
    "imageUrl": "/uploads/1783221252549-kakaotalk_20260704_142743744.jpg",
    "subtitle": "빅 or 뱅 유니콘 유니버스",
    "publishedYear": 2026,
    "status": "None",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/462896",
    "duration": "15-20",
  },
  {
    "id": "450039",
    "title": "BLUFFIT",
    "players": "2-6",
    "playTime": "15",
    "weight": 1,
    "imageUrl": "/uploads/1783221617089-ih3rtclezkqnxegj1vlt.webp",
    "subtitle": "블러핏",
    "publishedYear": 2025,
    "status": "None",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/450039",
    "duration": "15",
  },
  {
    "id": "302520",
    "title": "Hues and Cues",
    "players": "3-10",
    "playTime": "30",
    "weight": 1.1,
    "imageUrl": "/uploads/1783222045231-arcnszfsqv7xyfqerinu.webp",
    "subtitle": "색감과 직감",
    "publishedYear": 2020,
    "status": "None",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/302520",
    "duration": "30",
  },
  {
    "id": "451924",
    "title": "Biddle",
    "players": "2-5",
    "playTime": "15",
    "weight": 1.2,
    "imageUrl": "/uploads/1783222241117-8fegods8aod64eqriwm9.webp",
    "subtitle": "다이스 챌린저",
    "publishedYear": 2025,
    "status": "None",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/451924",
    "duration": "15",
  },
  {
    "id": "436843",
    "title": "Wolf Street",
    "players": "3-11",
    "playTime": "30",
    "weight": 1.3,
    "imageUrl": "/uploads/1783222455591-1exeounhg9paxkchpxkj.webp",
    "subtitle": "울프 스트리트",
    "publishedYear": 2025,
    "status": "None",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/436843",
    "duration": "30",
  },
  {
    "id": "467434",
    "title": "Abraca Who?",
    "players": "3-6",
    "playTime": "30",
    "weight": 2.5,
    "imageUrl": "/uploads/1783222594726-ou1o4dbugtlpmdphp0xo.webp",
    "subtitle": "아브라카 후",
    "publishedYear": 2026,
    "status": "None",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/467434",
    "duration": "30",
  },
  {
    "id": "454103",
    "title": "Magical Athlete",
    "players": "2-6",
    "playTime": "20-30",
    "weight": 1.2,
    "imageUrl": "/uploads/1783222728424-1779089850_698981_w300.jpg",
    "subtitle": "야단법석 달리기",
    "publishedYear": 2025,
    "status": "Owned by Friends",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/454103",
    "duration": "20-30",
  },
  {
    "id": "2310",
    "title": "Club Unlock",
    "players": "3-6",
    "playTime": "15",
    "weight": 1.3,
    "imageUrl": "/uploads/1783222899537-1684344879944687_lg_w1000.jpg",
    "subtitle": "캐시",
    "publishedYear": 1990,
    "status": "Owned by Friends",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/2310",
    "duration": "15",
  },
  {
    "id": "453526",
    "title": "Got Five!",
    "players": "2-4",
    "playTime": "15",
    "weight": 1.3,
    "imageUrl": "/uploads/1783223070066-1780497911_131980_w300.png",
    "subtitle": "알았다오",
    "publishedYear": 2026,
    "status": "None",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/453526",
    "duration": "15",
  },
  {
    "id": "411617",
    "title": "Quoridor Pac-Man",
    "players": "2-5",
    "playTime": "15",
    "weight": 1.5,
    "imageUrl": "https://cf.geekdo-images.com/2QqBn4MfWghniZok35dnsw__itemrep@2x/img/2cIQGbcdLgwGuUtS_SJAZnI2JHs=/fit-in/492x600/filters:strip_icc()/pic7974977.png",
    "subtitle": "쿼리도 팩맨",
    "publishedYear": 2024,
    "status": "Owned",
    "totalPlays": 1,
    "bggUrl": "https://boardgamegeek.com/boardgame/411617",
    "duration": "15",
  },
  {
    "id": "312484",
    "title": "Lost Ruins of Arnak",
    "players": "1-4",
    "playTime": "30-120",
    "weight": 2.9,
    "imageUrl": "https://cf.geekdo-images.com/6GqH14TJJhza86BX5HCLEQ__itemrep@2x/img/hX4PzEbU71mE4VPlo3l-mLFC2W0=/fit-in/492x600/filters:strip_icc()/pic5674958.jpg",
    "subtitle": "아르낙의 잊혀진 유적",
    "publishedYear": 2020,
    "status": "Owned",
    "totalPlays": 0,
    "bggUrl": "https://boardgamegeek.com/boardgame/312484",
    "duration": "30-120",
  }
];

const initialPlayers: Player[] = [
  { id: '08add8ea-3158-4a27-ac53-a17353dc20b0', name: 'Nahyup', group: 'User', imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nahyup' },
  { id: '6436820c-af37-4b2d-89e0-1644503329d2', name: 'Mom', group: 'Family', imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mom' },
  { id: 'f03f59af-84be-49b4-bf1c-882fd0344d4b', name: 'Dad', group: 'Family', imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dad' },
  { id: 'a6ace485-ec6f-46ca-ba76-f832d18fa43b', name: 'Sister', group: 'Family', imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sister' },
  { id: '87253b71-031f-4e92-bed9-3de068e52d21', name: 'Brother', group: 'Family', imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Brother' },
];

const customApiStorage: StateStorage = {
  getItem: async (_name: string): Promise<string | null> => {
    try {
      const response = await fetch('/api/data');
      if (!response.ok) return null;
      const data = await response.json();
      // data.json just contains the raw json string without the specific name key
      // but to mimic localStorage zustand expects it to return the whole serialized state
      return data ? JSON.stringify(data) : null;
    } catch (error) {
      console.error('Failed to load from auto-save API', error);
      return null;
    }
  },
  setItem: async (_name: string, value: string): Promise<void> => {
    try {
      // The value here is already a serialized JSON string from Zustand
      await fetch('/api/data', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: value,
      });
    } catch (error) {
      console.error('Failed to auto-save to API', error);
    }
  },
  removeItem: async (_name: string): Promise<void> => {
    // We don't really support 'removing' the file via the client in this setup, 
    // it would just save empty state.
    console.log(_name, 'has been deleted');
  },
};

export const useBoardGameStore = create<BoardGameState>()(
  persist(
    (set) => ({
      games: initialGames,
      players: initialPlayers,
      logs: [],
      stories: [],
      _hasHydrated: false,
      setHasHydrated: (state) => set({ _hasHydrated: state }),

      addGame: (gameData) => set((state) => ({
        games: [...state.games, { ...gameData, id: generateId(), totalPlays: 0 }]
      })),

      updateGame: (id, gameData) => set((state) => ({
        games: state.games.map(g => g.id === id ? { ...g, ...gameData } : g)
      })),

      deleteGame: (id) => set((state) => ({
        games: state.games.filter(g => g.id !== id),
        logs: state.logs.filter(l => l.gameId !== id) // Cascade delete logs
      })),

      addPlayer: (playerData) => set((state) => ({
        players: [...state.players, { ...playerData, id: generateId() }]
      })),

      updatePlayer: (id, playerData) => set((state) => ({
        players: state.players.map(p => p.id === id ? { ...p, ...playerData } : p)
      })),

      deletePlayer: (id) => set((state) => ({
        players: state.players.filter(p => p.id !== id)
      })),

      addLog: (logData) => set((state) => {
        const newLog = { ...logData, id: generateId() };
        // Increment total plays for the game
        const updatedGames = state.games.map(g => 
          g.id === logData.gameId ? { ...g, totalPlays: g.totalPlays + 1 } : g
        );
        return { logs: [...state.logs, newLog], games: updatedGames };
      }),

      updateLog: (id, logData) => set((state) => {
        const oldLog = state.logs.find(l => l.id === id);
        if (!oldLog) return state;

        const isGameChanged = logData.gameId && logData.gameId !== oldLog.gameId;

        return {
          logs: state.logs.map(l => l.id === id ? { ...l, ...logData } : l),
          // If the game was changed, decrement the old game's play count and increment the new one's.
          games: isGameChanged ? state.games.map(g => {
            if (g.id === oldLog.gameId) return { ...g, totalPlays: Math.max(0, g.totalPlays - 1) };
            if (g.id === logData.gameId) return { ...g, totalPlays: g.totalPlays + 1 };
            return g;
          }) : state.games
        };
      }),

      deleteLog: (id) => set((state) => {
        const logToRemove = state.logs.find(l => l.id === id);
        if (!logToRemove) return state;
        
        // Decrement total plays
        const updatedGames = state.games.map(g => 
          g.id === logToRemove.gameId ? { ...g, totalPlays: Math.max(0, g.totalPlays - 1) } : g
        );
        
        return { 
          logs: state.logs.filter(l => l.id !== id),
          games: updatedGames
        };
      }),

      addStory: (storyData) => set((state) => ({
        stories: [...(state.stories || []), { ...storyData, id: generateId(), createdDate: new Date().toISOString() }]
      })),

      updateStory: (id, storyData) => set((state) => ({
        stories: (state.stories || []).map(s => s.id === id ? { ...s, ...storyData } : s)
      })),

      deleteStory: (id) => set((state) => ({
        stories: (state.stories || []).filter(s => s.id !== id)
      })),
      
      importData: (data) => set(() => {
        return {
          games: data.games || [],
          players: data.players || [],
          logs: data.logs || [],
          stories: data.stories || []
        };
      })
    }),
    {
      name: 'dice-five-storage', // key in local storage/api
      storage: createJSONStorage(() => customApiStorage),
      version: 2,
      migrate: (persistedState: unknown, fromVersion: number) => {
        const state = persistedState as { games: Game[]; players: Player[]; logs: PlayLog[]; stories?: BoardGameStory[] };
        if (fromVersion < 2 && state.games) {
          // v1 -> v2: use BGG id as the game id, and remap play log references
          const idMap: Record<string, string> = {};
          state.games.forEach((g) => {
            const m = (g.bggUrl || '').match(/(\d+)\/?$/);
            if (m) idMap[g.id] = m[1];
          });
          state.games = state.games.map((g) => ({ ...g, id: idMap[g.id] || g.id }));
          state.logs = (state.logs || []).map((log) => ({
            ...log,
            gameId: idMap[log.gameId] || log.gameId,
          }));
        }
        if (fromVersion < 1 && state.logs) {
          // Remove legacy winnerId field; ensure winnerIds is always a string[]
          state.logs = state.logs.map((log: PlayLog & { winnerId?: string | null }) => {
            const { winnerId, winnerIds, ...rest } = log;
            return {
              ...rest,
              winnerIds: winnerIds ?? (winnerId ? [winnerId] : []),
            } as PlayLog;
          });
        }
        if (!state.stories) {
          state.stories = [];
        }
        return state;
      },
      onRehydrateStorage: () => (state) => {
        state?.setHasHydrated(true);
      },
    }
  )
);
